<?php

/*
	englist file:2001-12-6
	create time:2013-01-02 02:28:26
*/

return array(
'title'=>'Liu Zhi Ping, executive vice chairman of Guangxi Zhuang Autonomous Region, is investigated',
'class'=>0,
'cont'=>'December 6, 2001 (October 22), Government House, the executive vice chairman of Guangxi Zhuang Autonomous Region, Liu Zhibing being investigated. <br> 2001, the Central Commission for Discipline Inspection of the Standing Committee of the Guangxi Zhuang Autonomous Region, the former party, the Executive Vice President Liu Zhibing discipline illegal facts, the Central Commission for Discipline Inspection decided to give Liu Zhibing expelled from the party and approved by the CPC Central Committee approved . The Supreme People&#39;s Procuratorate has its legally arrested. <br> The investigation, Liu Zhibing discipline illegal facts: <br> First, the use of authority for other units or individuals for profit, accepting the Zhu Moumou et al bribes amounting to approximately 83.2 million. In 1992, Liu Zhibing should be of Liuzhou in a company manager, Zhu Moumou request, by Liuzhou City Finance Bureau in violation of regulations that guarantee corporate loans. In 1997, Liu Zhibing intervened public security organ smuggling 230 tons of white paper a case against the company, the company to evade taxes 69 million yuan. Zhu Moumou is thanks to Liu Zhi Ping, has sent Liu and his wife bribes totaling 300,000 yuan, HK $ 80,000 and $ 18,000. 1993-1999, Liu Zhibing should a plant manager in Liuzhou Moumou requirements, in violation of the provisions for the plant relief electricity bill of more than 2,000 million to secure government subsidies for 900,000 yuan to help the daughter of Zhang doing business. As a result, Liu has received Moumou sent bribes 170,000 yuan, $ 2,000. Liu Zhibing solve issues such as office promoted Wang 3, his wife received the other party to send a bribe of 110,000 yuan, HK $ 13,000. <br> used his powers to interfere with the judiciary of its investigation of cases of suspected criminal daughter. 1994-1999, Liu Zhibing his daughter, Liu Fang (already sentenced) for their participation in the of Liuzhou King issuing false VAT invoices tax fraud by the judicial authorities during the investigation, many times its excuse, interfere with judicial authorities handling the case to support its concealment of facts imply confrontation investigation. <br> III Liu Zhibing demoralization, long-term adultery with a married woman Moumou adverse impact. <br> In addition, Liu Zhibing also received cash gifts and other errors. The Central Commission for Discipline Inspection Committee (lssjt.cn) <br> meeting Liu Zhibing As senior leadership cadres, the use of authority, accepting bribes, gifts; to support suspected crime daughter confrontation investigation, interference with the judiciary normal handling the case; others to maintain long-term improper gender relations, etc., if the circumstances are serious, adverse impact. According to the relevant provisions of the Chinese Communist Party Disciplinary Regulations (Trial) \", approved by the CPC Central Committee decided to give Liu Zhibing expelled from the party. <br>'
);

?>