<?php

/*
	englist file:1877-12-6
	create time:2013-01-02 02:28:53
*/

return array(
'title'=>'Inventor Thomas Edison invented the world&#39;s first phonograph',
'class'=>0,
'cont'=>'December 6, 1877 (Landmarks in the winter in early b), inventor Thomas Edison invented the world&#39;s first phonograph. the <br> inventor Thomas Edison invented the world&#39;s first the phonograph <br> phonograph was born in 1877. King of the invention - Thomas Alva Edison, who invented the phonograph in the world is known around the world. <br> Thomas Alva Edison With the voices phenomenon caused by the vibration of the diaphragm in the telephone talkies, take a short needles were tested, and derive a lot of inspiration. Speak of the speed of the level of short needles can produce different fibrillation. Then, in turn, this quiver will certainly be able to issue the original voices. So he began to study voice retransmission. August <br> 1877, Thomas Alva Edison assistant Ke Ruixi to pattern made out of a large cylinder, crank, by phone and diaphragm strange machine. Thomas Alva Edison, pointing to this strange machine aide said: \"This is a talking machine, he took out a piece of tin foil, roll engraved with a spiral groove metal cylinder, so that the needle a light rubbing tinfoil rotation, the other end of the connection and the handset. Thomas Alva Edison shake crank facing by the phone began to sing \"Mary Had a Little Lamb, snowball child like a hair ...\". Over and over, the needle and the back light and leisurely shake crank. Then, the machine unhurried, round and round turning sang \"Mary had a little lamb ......\" with Mr Thomas Alva Edison sing exactly the same. Encounter a talking machine, turned aside aides was shocked speechless. <br> message \"talking machine\" was born sensation around the world. In December 1877, Thomas Alva Edison publicly perform the phonograph, the public opinion that he immediately hailed as \"the scientific community Napoleon Bonaparte, three great inventions of the 19th century, the introduction of the most exciting one. <br> Americans Thomas Alba Edison phonograph designed in 1877, is a the earliest recording device in the world. (Lssdjt.cn) <br> December 6 of the same year, Edison&#39;s assistant, mechanic John Ke Luxi produce the first prototype and prototype recording Edison singing \"Mary goats . \" <br> Edison and his invention of the early phonograph <br> find: recording the history of the first tone was born, friends who have the song \"Mary&#39;s goat\" music, history (LSSDJT) owners very very much hope that the collection, and some leave contact, thank you! <br>'
);

?>