<?php

/*
	englist file:2002-12-6
	create time:2013-01-02 02:32:03
*/

return array(
'title'=>'Scientists have discovered a nuclear reactor neutrino disappearance phenomenon',
'class'=>0,
'cont'=>'December 6, 2002 (Horse winter of early c), scientists have discovered a nuclear reactor neutrino disappearance phenomenon. Reference December 2002 at 5:00 pm, our scientists with Japan, U.S. counterparts at the same time announced a major discovery in neutrino experiments --- discovered neutrinos produced in nuclear reactors disappear the phenomenon, which means that neutrinos produced in the reactor oscillating neutrino into another is not detected. (L $ j¦Ó.c¨½) <br> this important experimental results is the experiment of kamLAND Three scientists from Japan, and the United States, (L $ dj¦Ó.§«§§T) in group come eventually confirmed the solar neutrino The occurrence of the oscillation, and the key to determine the neutrino oscillation parameters. <br> neutrino is a very small elementary particles, almost does not play a role with any substance, it is difficult to find and detection. The 2002 Nobel Prize in Physics is awarded to Raymond Davis, American scientists made significant achievements in the detection of cosmic neutrinos and Japanese scientist Masatoshi Koshiba. Sun&#39;s nuclear fusion to generate a large number of neutrinos Davis led solar neutrino experiments found in the 30-year probe of about 2000 neutrinos from the sun, but with the theoretical values &#8203;&#8203;compared to flow only to half of this is the famous \"solar neutrino loss mystery. Masatoshi Koshiba confirmed Davis&#39;s experimental results also confirmed the atmospheric neutrino disappearance. The major significance of the results achieved by the day, the United States, in Three scientists completed kamLAND experimental <br>: a new artificial neutrino source discovered neutrinos disappear, and the characteristics of the solar neutrino disappeared the same, which ultimately confirmed the solar neutrino oscillation, ruled out other explanations of solar and atmospheric neutrinos disappear. This is the first time in the international arena with artificial neutrino sources confirmed the solar neutrino oscillation phenomenon. This experiment also the first time quantitative given the unique solution of the solar neutrino oscillation parameters, and validation of the standard solar model is correct, to come to a positive conclusion of the neutrino mass is not zero. The same time, this experiment is the first time observed geological neutrinos emitted by the earth itself. (On com) In 1997 the start of construction kamLAND detector located in Japan 1,000 meters deep Shenkang, mine, the experimental group of nearly 100 scientists in Japan and the United States, the three countries use it to detect from more than 20 nuclear reactors produce neutrinos. The experiment began in February of this year, the Institute of High Energy Physics, Chinese Academy of Sciences researcher Wang Yifang, Chinese scientists participated in the experiment. <br>'
);

?>