<?php

/*
	englist file:2005-7-6
	create time:2013-01-01 23:34:57
*/

return array(
'title'=>'World famous physicist Huang Kun died',
'class'=>3,
'cont'=>'July 6, 2005 (, Yiyou June day), the world-famous physicist Huang Kun died. <br> world-famous physicist, foreign academicians, one of the founders of the solid-state physics and semiconductor physics, an outstanding educator, Chinese Academy of Sciences, the Royal Swedish Academy of Sciences and the Third World Academy of Sciences, China People&#39;s Political Consultative Conference National Committee, six, seven, eighth Standing Committee, China&#39;s total outstanding member of the Communist Party, the Jiu San Society members, the National May Day Labor medalist, the 2001 State Supreme Science and Technology Award winner , honorary director of the Institute of Semiconductors, Chinese Academy of Sciences Huang Kun died \"target =\" _blank \"> and Huang Kun academicians illness invalid, died in Beijing 16 3:17 pm, July 6, 2005, at the age of 86 years old. <br> Huang Kun academicians, <br> was born in 1919 in Beijing, is China&#39;s well-known solid-state physicist, the world-famous physicist in solid physical discipline, he made many significant contributions to pioneering , played an important role in promoting the development of solid-state physics, semiconductor physics, the founder of <br> Huang Kun has done pioneering work in some areas of solid state physics, 1947, Huang Kun proposed solid impurity defects lead to X-ray diffuse scattering theory, in the 1970s, has been confirmed by some foreign scientists and application to become a powerful means of the study of solid impurities defects, known as the \"Huang scattering. (lsjt.org) 1951 Huang Kun proposed the crystal phonon coupling of electromagnetic waves oscillation mode, Raman scattering experiments confirmed in 1963, was named polaritons, later found other substances similar vibration and electromagnetic waves coupling mode, also known as polaritons. the polaritons has become some of the optical properties of the analysis of solid foundation. Huang Kun equation, known as \"yellow equation. Huang Kun and M Born co lattice dynamics theory (Dynamical Theory of Crystal Lattices book was published in 1954, the Soviet Union in 1957, translated into Russian), is recognized as one of the disciplines authoritative book (history on the the cn) <br> since 1978 Huang Kun in solid theory research and has made new progress. concerning nonradiative transition adiabatic approximation and Demonstration of the equivalence of the static coupling theory, clarified than 20 years of international development of theory in this regard, the presence of some of the fundamental problems; Huang Kun proposed nonradiative transition phonon statistical regularity, may open up new directions for research in this area. these results are caused the concern of the international physics community. <br> Review: Chinese pride <br>'
);

?>