<?php

/*
	englist file:1966-8-6
	create time:2013-01-02 00:06:17
*/

return array(
'title'=>'Chinese medicinal chemists death of Zhao Cheng Gu',
'class'=>3,
'cont'=>'August 6, 1966 (June 20), Ping Wu, the Chinese medicinal chemists Zhao Cheng Gu&#39;s death. <br> <br> formerly known as Zhao Shimin. Chinese chemists. Chinese Academy of Sciences. December 11, 1885, was born in Jiangyin, Jiangsu, August 6, 1966 and died in Shanghai. Juvenile persons shall be cited as the scholar, barns Health, after the change from the new school, in 1906 admitted to official charges in England, in 1912, a master&#39;s degree from the University of Manchester, and a doctorate in the University of Geneva, Switzerland, in 1914. 1916 French Rock pharmaceutical technician, director of research, the design of the production process of the local anesthetic procaine, patented. He returned to China in 1922. He was the Nanjing Higher Normal, Southeast University, Department of Chemistry, Professor, Peking Union Medical College, Acting Director, Professor, Department of Pharmacy. 1932, Ying Li Shizeng invited, founder of the Peking Institute of Drug Research Institute, he served as Research Fellow and Director, and was elected to the council members at the Academia Sinica. 1949, served as the Chinese Academy of Sciences Institute of Organic Chemistry the Drug Research Office, the director of the Institute of Materia Medica, Chinese Academy of Sciences and other staff, a pioneer in the application of scientific methods for herbal medicine research in China, in phytochemical research, especially alkaloids fractional crystallization is unique. Separating the resulting Corydalis prime B has formally included in the Pharmacopoeia, clinically as analgesic sedative; separating the resulting of febrifugine C prime, with quinine 148 times higher antimalarial activity; the separation koumine B can be used as physiological laboratory reagents. Had studied more than 30 kinds of Chinese herbal chemical composition, many new alkaloid crystals, some of which are recommended clinical use. Establish a system the study finishing motherland medicine scientific method, and was the second prize of National Natural Science Award in 1982. Has also solved penicillin potassium salt crystallization method, to make penicillin smooth put into. Guide the design of test synthesis process of a local anesthetic procaine. <br> 1955 was elected to the Chinese Academy of Sciences. <br> <br> Zhao Cheng Gu&#39;s death \"target =\" _blank \"> the Zhao Cheng Gu original separation extraction method is very effective. <br>'
);

?>