<?php

/*
	englist file:1940-10-6
	create time:2013-01-02 01:47:11
*/

return array(
'title'=>'New Fourth Army was Huangqiao decisive victory',
'class'=>0,
'cont'=>'(Gengchen September sixth days), October 6, 1940, the New Fourth Army was Huangqiao decisive victory. participate of Huangqiao anti stubborn battle forces (Riding the first person to Chen Yi, <br> riding second man, Su Yu) on the morning of October 6 <br> in 1940, the New Fourth Army stopped the KMT army Han Deqin Ministry the chase, the initiative to end Huangqiao Battle. New Fourth Army captured Huangqiao Han Deqin first send someone negotiations with the New Fourth Army, intended zone the following and damaged agreement, the New Fourth Army offensive. New Fourth Army attack, repel the Korean Ministry of wells momentum captured Jiangyan. captured Jiangyan <br> In order to maintain the political initiative, the New Fourth Army contacted representatives of all walks of life gentry China issued a call to re-open negotiations, settlement of disputes, and on September 30 to exit Jiangyan meet the Han Deqin to Han Deqin the proposed negotiations condition. However, Han Deqin, as the New Fourth Army, peaceful settlement of disputes as weakness to launch an attack on the same day to the New Fourth Army. <br> New Fourth Army First fight Ming-Yang Li, Li Changjiang the Sulu Но guerrilla corps, Chen Tai Yun tax police groups, and other KMT army to remain neutral, then the concentration of forces, fighter diehard troops in motion. After the fighting broke out, the first column after three hours of fighting, wipe out the Han Deqin, the main independent six Brigade, cut off the right-wing of the Han Deqin offensive. Then, the first column and the second column surround and annihilate the its thirty third main divisions, wild Wuji along the eighty-ninth the Army military and third forty-nine of trip east full siege. <br> After a night of fierce fighting, the 6th morning, Han Deqin eighty ninth Army military was completely wiped out, the eighty-ninth Army commander Li Shouwei fell into the water and died, the third forty-nine Brigade also most was destroyed, Korea Deloitte rate of more than a thousand people to Xinghua fled. To build on this, the New Fourth Army go after Han Deqin remnants of the occupation of the MSC. Arrive Dongtai, the New Fourth Army, the principle of \"rational, beneficial, and restrained\", on the same day to stop the chase, took the initiative to end this battle. (Today in History TodayOnHistory.com) <br> Huangqiao decisive, total F Kuomintang army 1.1 million people, more than 10 prisoners, head over officers, including its thirty-third division of the Qi-ninety Miao Ruilin nine brigade, the length of the gun seized more than 3,800 pieces, 189 light machine guns, three mountain artillery, mortars, 59, as well as large quantities of ammunition and military supplies. the participate Huangqiao Battle against stubborn <br> forces <br>'
);

?>