<?php

/*
	englist file:1843-7-9
	create time:2013-01-01 23:47:12
*/

return array(
'title'=>'Outstanding nerve tissue scientists and pathologists the Gore quarter&#39;s birthday',
'class'=>4,
'cont'=>'July 9, 1843 (June 12), mao, scientists and pathologists Outstanding nerve tissue the Gore quarter&#39;s birthday. <br> Gore quarter&#39;s Birthday \"target =\" _blank \"> Gore quarter is an outstanding neuroanatomist nerve tissue scientists and pathologists He founded the famous chromate - nitrate silver method for the study of the central nervous system has opened up a broad road and one of the basic theory of modern biological science - neuron doctrine is established on the basis of his research in 1906, he shared with caja Connaught Bell biology and medicine prize, enjoys a worldwide reputation for medical scientists in Italy. <br> 1843, Gore quarter Ke Taina born in Italy Bly Blanca his father was a medical practitioner, and later settled in a village near the camp Monrovia City in 1865, Gore quarter graduated from the allocation Via University. late in medical school, he went to Lombardy Professor Luo Sha psychiatric hospitals to participate in clinical treatment when the nervous system is a pessimism: vague structure, vague symptoms, the more ambiguous function of \"lack of confidence in the science of the nervous system, but Gore quarter due to the impact of Lombardy Rosa, despite difficulties, determined to study the nervous system microsurgical anatomy, in order to understand the physiological function, as a lifelong career. <br> 1872, Gore quarter for a living forced to a small cures of incurable diseases hospital Dr. Ren Zhuyuan Even so, he still establish a laboratory, in her kitchen with a microscope and some simple tools, candlelight every night, to concentrate on nerve tissue staining study of his epoch-making (ie chromate - silver nitrate method). use it later came to be is the microscopic structure of the nervous system, the concept of a revolution, is also an ideal way to study the neural tissue. Gore the quarter master staining method to study the structure of the brain and spinal cord, and many achievements in 1885 - In 1886, his magnum opus, \"subtle anatomy of the central nervous system\", which is an immortal work immediately after the release of attention, not only in France, second edition, was translated into German and English. <br> Ge the Seoul quarter is not only a scientist, but also a very enthusiastic doctor who has patients come to seek treatment, he do all responsive once his son was sick, he has to go all out for the seriously ill governance disease, his wife saw this case and he almost got into a fight after he explained: \"son&#39;s pain is no doctor can cure everything, she do not need me, not to mention other doctors know that the patient is Gore quarter son, who would not particularly careful it? \"his medical ethics, has won the praise of the people. January 21, 1926, Gore quarter died. <br>'
);

?>