<?php

/*
	englist file:1961-8-13
	create time:2013-01-02 00:46:18
*/

return array(
'title'=>'&quot;Berlin Wall&quot; built',
'class'=>0,
'cont'=>'August 13, 1961, three days (July 1901), \"the Berlin Wall\" built. guards and police guarding the border <br> laying barbed wire constitutes walled base and precast concrete blocks <br> of Berlin, the German capital. An area of &#8203;&#8203;883 square kilometers and a population of 3.43 million (1993). Before the 13th century, Slavs settlements. In 1415, the capital of Brandenburg Hou. In 1701, the capital of the Kingdom of Prussia. The capital of the German Empire in 1871, and developed into a commercial, industrial, and transportation center. The capital of the Weimar Republic in 1919. After the Hitler Germany surrendered in May 1945, according to the Yalta Agreement and the Potsdam Agreement by the partition of the four countries of the Soviet Union, the United States, Britain, France and occupied Germany and Berlin, and the establishment of four zones of occupation. The United States, Britain, France, in June 1948 to merge the three countries occupied territories. The same year, the Soviet Union occupied zone set up the the big Berlin provisional democratic government set up a West Berlin government; United States, Britain, and France occupied territories, to Berlin then split into East and West Berlin in two parts. (L $ j¦Ó.c¨½) 1961 8 13 2011 the German Democratic Republic in the construction of the Berlin Wall between East and West Berlin. East Berlin became the capital of the German Democratic Republic, the national political, economic, cultural, and transportation center. Area of &#8203;&#8203;403 square kilometers and a population of 1.25 million (1987). West Berlin area of &#8203;&#8203;480 square kilometers and a population of 1.88 million (1987), 1945 has been under the control of the United States, Britain, and France. September 3, 1971, the four countries of the United States, Britain, France, the Soviet Union signed the Quadripartite Agreement on West Berlin problem. The provisions of the Agreement: \"West Berlin, Federal Republic of Germany is an integral part of, the future does not belong to the jurisdiction of the Federal Republic of Germany, but to maintain and develop links between western Berlin and the Federal Republic of Germany; international agreements signed by the Federal Republic of Germany Expands to Berlin West End . \" From time to time a dispute about the status of the parties against their own favorable interpretation of provisions of the agreement are united Berlin. And opening of the Berlin Wall in November 1989. October 1, 1990, the four countries and the two German Foreign Minister announced the end to the four countries in the exercise of power in Berlin and Germany. After German reunification, the Parliament decided in June 1991 in Dublin. <br> <br> East Germans risked trying to go to the Western <br> Berlin Wall reinforcement <br> on both sides of the Berlin Wall, stocked with a 100-meter-wide no man&#39;s land, set up warning signs, thus became the witness of the East-West Cold War. <br>'
);

?>