<?php

/*
	englist file:1505-10-27
	create time:2013-01-02 02:03:52
*/

return array(
'title'=>'Russian centralized state founders - Ivan III died',
'class'=>3,
'cont'=>'In (Yi Chou started this October), October 27, 1505, the Russian centralized state founders - Ivan III died. <br> a 19th century painter&#39;s works, the performance of Ivan III refused tribute scene. <br> the 15th to the 16th century, the Russian State by feudal separatism gradually move toward unification. , Ivan III is worth mentioning that in the Russian State unify this mission process. <br> Ivan Moscow Grand Duke Vasily eldest son, was born January 22, 1440, his childhood intelligence sly. Vasily II war lost eyes, bit \"blind Archduke\". Ivan the age of 10, his assistant, blind father to rule. In 1462, his father died, Ivan throne, known as \"Ivan III. <br> Ivan III to the throne, the Grand Duchy of Moscow after the business of his grandparents and parents have been very powerful. Ivan III inherited their career, fighting for the completion of the unification of the Russian State. His first goal is to mergers Novgorod Feudal Republic. Novgorod Republic, the land vast, rich resources, land and water transportation across the northwest corner of the male, and a great deal of independence. In In May <br> 1471, Ivan III, held in Moscow, Novgorod meeting ready to attack, called on the participants of the princes, nobles, bishops and generals to carve up the piece \"plump stolen goods. He dispatched three armies completely defeated in battle Scotia Long River on July 14 Novgorod, forcing the signing of the Treaty, to ensure that the \"good faith and strictly uphold the rule of the Grand Duke. In 1475, Ivan III provoking and Novgorod grassroots struggle of the upper nobility, sending its troops to Novgorod. In 1478, Iraqi III the ultimate elimination of the Republic and its territory incorporated into the Duchy of Moscow. Soon, the Duchy of Tver was defeated, surrender the Duchy of Moscow. After other kings and almost no resistance was Bianchu to purely local Executive. Russian Duchy of such a split for more than 300 years, basically unified under the command of the Moscow Grand Duke Ivan III. Ivan III in the completion of the basic unity after the elimination of the internal and external problems, the drastic domestic reform. He carried out the reform of the administrative bodies, to strengthen the centralized state organs, the implementation of military reform, the establishment of a direct control of the country by their own standing army; implementation of fiscal reforms, unified currency, coinage rights Archduke proprietary. He basically completed the domestic reform, relying on powerful national strength, began to wage the war of foreign expansion. (L $ dj¦Ó.c¨­m) to enter Lithuania, sent troops to the coast of the Baltic Sea, Dongzheng to the Tobol River, Irtysh and Ob River basin, until October 27, 1505, died. Not only is he the founders of the Russian centralized state, is also the originator of the external expansion of Tsarist Russia. (History today www.lssdjt.com) <br> Ivan IV <br>'
);

?>