<?php

/*
	englist file:1931-5-27
	create time:2013-01-01 23:04:24
*/

return array(
'title'=>'KMT Chiang Kai-shek sent a separate National Government',
'class'=>0,
'cont'=>'May 27, 1931 (, Xinwei, April 11,), the KMT&#39;s Chiang Kai-shek sent a separate National Government. established <br> Guangzhou National Government, Wang Jingwei presided the parade In in 1931, Wang Jingwei energized KMT overseas party headquarters, known as the Chiang Kai-shek Woe Party harm the country, and even \"violent cross-Day words distressed \", is now Guangdong rose discuss Jiang, things have been so far, should be based on total Chapter, convene an extraordinary National People&#39;s Congress, to solve everything.\" (Today in History TodayOnHistory.com) <br> the first Eighth Route Army commander KMT Guangdong Jitang and teachers Yu Han-mou, Hong Han screen, the fourth Fleet Commander Chen Ce joint energized in response to the April 30 ancient Ying-fen impeachment Chiang Kai-shek&#39;s energized requirements Chiang retire. on <br> 11 the KMT Guangdong, Guangxi Province generals Li Tsung-jen, Pai Chung-hsi, Zhang Fakui, Lee goods cents energized denounce Chiang Kai-shek \"since entrenched Nanjing Central burglary Party harm the country.\" Expresses its determination to discuss Jiang the \"rendezvous Yangtze Diding Jinling,\" rescue party to save the country \". (On com) <br> the 27th KMT first, second, third central executive, the provisional members of Wang Jingwei, Sun Ke, Tang Shaoyi Lu Zou, Eugene Chen, Jitang, Yan Xishan, Feng Yuxiang, the ancient KMT extraordinary meeting of the members of the Central Executive Supervisor should be fun, Linsen, Li Tsung-jen, Li Fulin held in Guangzhou. The meeting adopted the Declaration of the Conference the Wang Jingwei drafted very, decided another group of the National Government, announced the National Government memorandum to deny the legitimacy of the government of Chiang Kai-shek in Nanjing. The meeting decided that the initiative to convene the KMT four. In May 27, the Chiang Kai-shek sent in Guangzhou, has resolved to set up a national government issued the Declaration of the Establishment. The same day, announcing the Government&#39;s memorandum of 11 presumed the 17 members of the National Government, Tang Shaoyi, Wang Ching-wei, Ku Ying-fen, ZOU Lu, Sun Ke Standing Committee of the 5 people, the rotation of the office of President of the Council of State. On May 28, the inaugural ceremony of the Guangzhou National Government Members inauguration. <br> Kuomintang Central Executive Supervisor member photo <br>.'
);

?>