<?php

/*
	englist file:1970-10-28
	create time:2013-01-02 02:09:06
*/

return array(
'title'=>'China-aided Tanzania-Zambia Railway commenced',
'class'=>0,
'cont'=>'October 28, 1970, September 29) (Gengxu years, the China-aided Tanzania-Zambia Railway commenced. , <br> 1970 10 28 officially commenced construction of the Tanzania-Zambia Railway, China, Tanzania, a symbol of (而身d芋y身里h貝 $ 而身ry.c身m) Zambia friendship between the peoples, unity and cooperation. <br> China, Tanzania, Zambia and the two peoples enjoy traditional friendship, as early as in the 15th century, Chinese navigator Zheng He had long voyage along the coast of East Africa. Now hanging in the National Museum of Tanzania, one of Zheng He&#39;s voyages the ship diagram, the museum displays a lot of Chinese ceramics. China and Tanzania, and Zambia in 1964 to establish diplomatic relations. Since then, the three countries the continuous development of the friendly relations of cooperation and friendship. Tanzania-Zambia Railway <br> is based on the September 1967 Japan-China, Tanzania, Zambia jointly signed agreement to work together to build. This rail link Tanzania and Zambia, a total length of 1860 km, which is about 960 kilometers in Tanzania, Zambia is about 884 km. Many mountain valleys and swamps along the Tanzania-Zambia Railway, arduous project, totaling 320 bridge across the board, dug tunnels and Myeongdong 26. The peoples of the three countries make joint efforts to overcome difficulties, the railway was built in 1976 and opened to traffic. <br> Tanzania-Zambia Railway began operations coincided world recession, the Western countries to pass the economic crisis, Tanzania, praised the two countries&#39; economy has been a great impact, growing difficult. Chinese experts have traveled, repeatedly came to the Tanzania-Zambia and China, the spread of technology and technical guidance, and is also involved in the management of the railway. Despite the difficult living conditions and physical exertion to find ways to have done a lot of work, after investigation, a number of positive recommendations. They take the lead in the work and labor, potential hazards, loopholes and improve various rules and regulations. Chinese experts also met with the Tanzania-Zambia Railway years cargo workers with the investigation and has opened a supply. Through the efforts of the three countries, the integrity of the Tanzania-Zambia railway locomotives and vehicles rate has improved, various accidents gradually reduce passenger and cargo traffic has increased significantly. The new meteorological TAZARA has won the praise of the people. Tanzania, Zambia and Chinese public opinion that TAZARA has a huge potential for transport. <br> Tanzanian Prime Minister Salim, as Chatan Zambia Railway Administration, in particular, praised the contribution made by the Tanzania-Zambia Railway. Today, experts, Tanzania, Zambia three countries are increasingly trying to explore new methods and via the railway. <br>'
);

?>