<?php

/*
	englist file:1887-5-28
	create time:2013-01-01 22:32:39
*/

return array(
'title'=>'Chinese poet Liu Yazi birth',
'class'=>4,
'cont'=>'May 28, 1887 (Chinese New Year leap in April sixth days), Chinese poet Liu Yazi born. <br> of Liu Yazi <br> Liu Yazi (1887.5.28 - 1958.6.21) Suzhou Wujiang Li Azeri, Chinese poet, the KMT leftist. Nanshe promoters. Formerly known as comfort high No. security, such as the human rights of, change the word, number Asia House, renamed abandoned illness, the word Cassino, the number of sub-sub, Jiangsu Wujiang people. Early years in rural tour from Chen Qubing, Jin Tianyu, 1905 Learning Preserving. After the Restoration League to Shanghai. Cn] [the history of the United League. Founded and presided over Nanshe. Republic of China, a former Presidential secretary of Sun Yat-sen, the Chinese Kuomintang Central monitors, Shanghai the Annals Museum curator. After the April 12 coup, wanted to flee to Japan. Back in 1928, Chiang Kai-shek activities. Engaged in anti-Japanese democratic activities in the War of Resistance Against Japan, (L $ dj¦Ó.§«§§T) with the Soong Ching Ling, He Xiangning, a former Chairman of the Central Standing Committee of the Revolutionary Committee of Chinese Kuomintang Chairman and the Commission, the central executive director of the Federation of the Three Principles of the People comrades, the Central Executive Committee of the China Democratic League . 1949 to attend the first plenary session of the Chinese People&#39;s Political Consultative Conference (CPPCC). After 1949, he served as a member of the Central People&#39;s Government, member of the Standing Committee of the National People&#39;s Congress. Singing poetry generous Yigong word. With grinding sword room the poetry set \"and\" grinding the sword room Wen recorded, otherwise of Liu Yazi Selected Poems \"line World. <br> Liu Yazi emphasis on the ideological content of literature, he opposed sighed the old sigh Peel personal theme chant, also object to the granting of the circumstances of the word Wind hang around wiping month. Poetry with his advocating Tang Yin, inherited Xia Wanchun, Gu, [on cn] Gongzizhen 3 denigration to Tingjian School of Jiangxi. Word wind, he respected Xin Qi-ji, denigration Wu Wenying. , (L $ j¦Ó.c¨½) in the style of writing on his opposition to Han Yu and Tongcheng. Liu Yazi a the political weapons poet poetry. His poetry, in close connection with the development of the bourgeois-democratic revolution, and filled with a strong sense of patriotism, democratic passions with distinctive battle. In the extensive make friends in the revolution, the Liu Yazi wrote a large number of the Wye people poetry gifts Friends of poetry. The heroic struggle of the revolutionaries Liu poem full of impassioned air of the troubled history of this struggle and his poems with a gloomy desolation of style. After the Revolution, Liu Yazi poetry theme into criticism of this revolution is not complete. After the May Fourth Movement, his creation into a new era, and has been singing to the founding of the People&#39;s Republic. <br>'
);

?>