<?php

/*
	englist file:1944-5-28
	create time:2013-01-01 22:40:42
*/

return array(
'title'=>'Luoyang was occupied by the army',
'class'=>0,
'cont'=>'May 28, 1944 (, Jiashen leap in April, the seventh day), Luoyang military occupation. Henan battlefield <br> on the Japanese body <br> January 28 morning, the Japanese tank troops broke into a powerful artillery in Luoyang City. After the Japanese 12th Army belongs to the thirty-seventh, sixty-second and sixty-third, Hundred divisions and other units to powerful offensive, the occupation of Zhengzhou, Xinzheng, Changge, Xuchang, Yancheng towns, Henan province to get through on the morning of May 9, Ping-Han Railway. At the same time, the Japanese captured close County west Pinghan Road, Yuzhou, Jiaxian, Yu Chau. Japanese North China Army again part of the 12th Army to continue the West guilty in jindongnan army sixty-ninth, twenty-seventh Division Ministry south, causing flank Luoyang trend. May 12, the Kimura Chiyoda too rate Infantry fifty-ninth brigade occupied mianchi cut the Longhai Railway, Luoyang become isolated city in the Japanese encirclement. Meanwhile, Japanese 12th Army launched a campaign of Luoyang. (Lsjt.net) <br> positions of the thirty-sixth Army of the Chinese garrison his troops relying fortifications damaged tenacious fight against the whole bag of rice and salt, and finally even moving in charge to do the parapet and obstacles to the Japanese killing. But in the Japanese heavy artillery impact of defenders ammunition will do all the disruption of communications in the city, and finally failed to block the Japanese attack. (History TodayOnHistory.com) April 17, <br>, close to the Japanese, the Executive Department of Luoyang completely disordered, the the theater commander Executive Jiang Dingwen and senior generals have to rush to transport dependents to go to Shaanxi, count enemy killed in Luoyang to Tongguan railway line up to more than a thousand people. The Mianchi fall enemy captive Quguan the Mrs., Miss, and that more than 300 people. Luoyang, the loss of more than 20 million packages of food, a theater car more than 350 vehicles drove off the enemy intact. Was destroyed the defenders of Liu Maoen 6,000 4,000 collaborators, and the remainder are cleared. Sun Wei, such as the Ministry of Department of a theater remaining the most complete, also lost more than half, the remaining people. A General Department of 15 divisions, only 20,000, less than 10,000 rifles. A theater all heavy weapons, artillery, heavy machine guns, ammunition depots were all wiped out, Jiang Dingwen rate of the Executive Department of Luoyang fled to Luoning actually left a driver and hired two farmers, after accommodating 11 soldiers as guards people attack scattered. \"Collapsibility situation of panic disorder, since the War of Resistance Against Japan is real only see\". <br> thousands of refugees climbing train leaving the theater, eager to escape the war <br> Lawrence Ah Mon Army the twenty-teacher the fifty-eight Regiment colonel stick Henan hsiang County heroic donate donate <br>'
);

?>