<?php

/*
	englist file:1919-6-28
	create time:2013-01-02 00:04:56
*/

return array(
'title'=>'China refuses to sign the Treaty of Versailles',
'class'=>0,
'cont'=>'(Kang Xi June, the first day), June 28, 1919, China has refused to sign the Treaty of Versailles. the <br> students to distribute leaflets <br> in the streets on June 27, the evening, 1919, in the last moments before the German peace treaty signing, Wellington Koo develop a final compromise. The scheme proposal before the peace treaty signing, issued an oral statement by the representative of China, after the signing of the declaration shall be without prejudice to the eventual proposal Shandong. <br> the following statement: \"Today, before the conclusion of peace treaty signed with Germany, the Republic of China Plenipotentiary due to the approximately 156th, of one hundred fifty-seven and one hundred fifty-eight of paragraph makest inheritance rights of Germany in Shandong, is not so China&#39;s resumption of its territorial sovereignty, real unfair, (而身d芋y身里h貝 $ 而身ry.c身m) hereby declare the name of his government: their signing the treaty does not prevent the future at the appropriate time, the attention of Shandong reconsideration. Prejudice to the interests of permanent peace in the Far East also unfair results. Lu Cheng-hsiang immediately approved the statement. <br> 6 months 28 signing ceremony, held in Germany and about. The morning of June 28, Minister to France Hu Wei, the Chinese That statement brought to the consultation and will be the return of the Secretary-General to the Hangao still totally rejected. The Chinese delegation, then the public with the decision, not to the signature \". <br> day, Lu Cheng-hsiang, Zhengting, Wellington Koo, Wei Chen group (Sze long after the law) jointly call the Government, the report refused about the situation, pointed out: \"The matter of losing concessions. Initially advocated change the rider, but also refused; replaced about outside, they refused; instead of using only statement, do not retain the words, they do not allow; last resort, to a temporary partition function declaration can not inject about, do not allow; signature impede future draws for reconsideration and so on. It turned out that this completely rejected noon. ...... Imperious to this General Assembly, not here with a little care I national fiber micro-decent Camps wins indignation! Weak nation negotiations, the beginning of contention has finally enabled almost turned into a convention. The Ruozai forbear signature, our future will be more diplomatic speak. ...... A last resort, then do not go to the signing. \"<br> Reject about the decision of non-governmental instructions, so that the Chinese delegation immediately prepared notified by president statement saved my final decision for Germany about the right language, the aunt too aggressive. Finally, four Plenipotentiary grounds of \"Bong occupational stateless\", the government is removed from office, \"delivered the punishment. <br> masses hold high the \"do not admit the signature\" slogans <br> Minister to France of Hu Brad <br>'
);

?>