<?php

/*
	englist file:1938-7-28
	create time:2013-01-01 23:10:13
*/

return array(
'title'=>'Peruvian President Fujimori&#39;s birthday',
'class'=>4,
'cont'=>'July 28, 1938 (Tiger years in July, the first two days), the former Peruvian President Alberto Fujimori&#39;s birthday. the <br> Fujimori and Susana family portrait before the divorce Alberto Fujimori, <br>, July 28, 1938 Born in Lima, a Japanese expatriate family, his father in 1936 by the Japanese Okinawa immigrants to Peru. Fujimori was educated at the the Lima National Agricultural University, graduating in 1961, and subsequently went to study in Europe and the United States, respectively, to obtain a master&#39;s degree in the University of Wisconsin and the University of Strasbourg, France. After returning home, he three times in a row as the person in charge of the peasants and workers of the Agricultural University, Department of academic plans. Fujimori also TV show host, proficient in English, French and Japanese. He and his wife of Japanese ancestry, Su Sana has been divorced, gave birth to four children. In July 1989, Fujimori with a number of non-party personages created Peru reform 90 \"campaign, the slogan\" honesty, technology, industrious, put forward \"is different from the leftist the different rightist\" campaign platform . Fujimori participated in the 1990 national elections, and was elected president. Fujimori took office on the eve of Peru&#39;s economic situation is extremely severe, sharp social contradictions rampant nationwide strike, the teacher&#39;s strike, strike after another, terrorist activities. Fujimori took office, composed of multi-party cooperation has the color of technocratic cabinet, military and police generals big adjustment and restructuring of the government team several times. His government to work on accelerating the privatization of state enterprises and to strengthen the two major events of the struggle against terrorism, have achieved positive results. Peru when the two major anti-government guerrillas \"Shining Path\" and \"Tupac - Amaru Revolutionary Movement leader and a group of leading backbone has arrested the guerrillas suffered heavy losses. <br> economic, Fujimori implemented a series of reform measures, to overcome the hyperinflation, economic recovery and growth. Hold new elections in Peru in 1995, Fujimori reelected president. According to the Peruvian Constitution stipulates that the president can only be re-elected term, otherwise in violation of the principles of democracy. I Fujimori claimed, he was first elected in 1990, do not count, because it was before the promulgation of the new constitution, and the constitution in three years after the entry into force. Fujimori&#39;s supporters also do this through a legal interpretation of the legitimacy of this election. <br> Therefore, in 2000, he wins in the election, continue to serve as president. during <br> Fujimori&#39;s visit the Browse the Great Wall <br> \"Beijing roast duck taste really good. \"<br>'
);

?>