<?php

/*
	englist file:1969-8-17
	create time:2013-01-01 23:48:02
*/

return array(
'title'=>'The world&#39;s largest gathering of hippies',
'class'=>0,
'cont'=>'August 17, 1969 (, Jiyou In July, the fifth day), the world&#39;s largest gathering of hippies. <br> Jimmy - performances of Hanruikesi the most memorable shows in the Woodstock Music Festival. When he played the U.S. national anthem, the excitement of the audience will guide the country to Vietnam&#39;s Stars and Stripes shredded <br> 1968 15-17, held a large-scale music festival in Woodstock. The festival has become the world&#39;s largest hippie gatherings, 400,000 young people, regardless of traffic congestion, a shortage of food and drinking water and heavy downpour difficulties, shaking like mad with a blare of music. They belted long hair, wearing bell bottoms or coarse cloth batik shirt, sexual intercourse in the mud in wet sleeping bags, smoking marijuana, like breathing air. to <br> with Woodstock Music Festival throughout the United States, Europe and around the world, The young hippies have sent these programs has become a powerful symbol of unity of the generation. They seek the love of humanity and peace in an extreme way. <br> number of people than the people expected to be more than twice. Reported that traffic stalled on the venue around 20 mpg on the highway. Thousands of discarded cars, after the New York town of Bessel, market places flock near the Woodstock Music and Arts. This is one belonging to Marcos - Elias Siegel&#39;s area for the 600-acre dairy farm. Marcos loans designed to move this piece of land. <br> people to participate in the Music and Arts Festival is a series of performing artists attracted by their names reads very much like a popular musician celebrity Dictionary. These people include, Jefferson - °¬¶ûÆÕÀ³¶÷, Ritchie - Havens;; gratitude deceased; the Kerry Providence, Crosby, Stills, Nash and Young; - Clearwater - Liweifuer; Huo ; Bender; Jane Nice - Joplin and Jimi - Hendrix. <br> \"make love, not war\" - this is the slogan of the generation 6O late, but also their way of life. All for peers far in the quagmire of Vietnam combat, I do not know the protest or satire. <br> 40 million American youth gathered in Woodstock, two amazing big rainstorm so that they become crazy in the mud. Call of \"love and peace\", the festival has become a strange antiwar <br> \"make love, not combat\" anti-war revolutionary slogans heard throughout the venue. The many couples naked, and even making love in public, this return to basics way back to Adam and Eve&#39;s era war policies of the U.S. government spurned and angry <br> in the tremendous performances platform, music, poetry readings throughout the night, deafening loudspeakers, 400,000 pairs of dancing feet around riding into a muddy. After nearby farmers demanded the government compensation trampled fields and many mental damages can not sleep. This is the high view of many on the shelf of the stage. <br>'
);

?>