<?php

/*
	englist file:1933-1-17
	create time:2013-01-01 22:25:22
*/

return array(
'title'=>'Chinese Communist Party issued a declaration: stop the civil war agreed anti-Japanese',
'class'=>0,
'cont'=>'January 17, 1933 (the twelfth lunar month 22) Renshen CPC issued a declaration: to stop the civil war to unite against Japan. <br> Since last winter, the Japanese army massacred a large number of the Volunteer soldiers <br> 17, 1933, Mao Zedong, Zhu De, \"against the Japanese imperialist invasion of North China, and is willing to under three conditions national army anti-Japanese Declaration. \" <br> declaration said: the people of the whole of China! Japanese troops invaded the north, causing the whole batch and residents killed, the destruction of the city and the countryside, as well as pain and increased famine. Severance with the massacre, the Chinese soldiers because of Chiang Kai-shek, Zhang Xueliang and non-resistance and surrender, because of the oppression of their anti-Japanese soldiers, a large number of dead in under the guns of imperialism. The Kuomintang help further massacres in Japan, at the same time they are using everything in their power to suppress the anti-imperialist struggle and the Volunteer of the organized armed forces. once again remind the Chinese people of the <br> Chinese Soviet government and the Revolutionary Armed Services Committee, has called on people across the country in April last year, together with the armed struggle against Japan, Chiang Kai-shek to answer this call is to mobilize all the army offensive Chinese workers &#39;and peasants&#39; government and the Workers &#39;and Peasants&#39; Red Army, rather than go against Japanese imperialism. (Lssjt.cn) <br> Chinese Soviet government and the Workers &#39;and Peasants&#39; Red Army Revolutionary Military Committee of the Chinese people before the Declaration: Under the following conditions, the Red Army ready to combat agreements entered into with any armed forces against the Japanese imperialist aggression. (L $ dj¦Ó.¨­r¨À) <br> (1) immediately stop the offensive of the Soviet area; <br> (2) immediately to ensure the democratic rights of the people (of assembly, freedom of association, freedom of speech, publication, free to strike); < Now armed populace br> (3) the creation of armed Volunteers, to defend and fight for independent reunification and territorial integrity. We demand that the Chinese people and soldiers, to respond to the call, to carry out the the armed nationalist revolutionary war against Japan and all imperialist. (History. Cn) <br>'
);

?>