<?php

/*
	englist file:1968-9-17
	create time:2013-01-02 00:41:14
*/

return array(
'title'=>'Hong Kong artist Weng was born',
'class'=>4,
'cont'=>'September 17, 1968 (, Shigenobu leap July 25), the Hong Kong artist Weng was born. September 17, 2011 <br> 1968, Weng was born \"target =\" _blank \"> Yvonne Yung (Hong Kong artist, 1989 Miss Asia champion) was born. <br> Veronica Yip three successful upper example I do not know that the number of actress bangs, eager to become a phenomenon in 1993. Loretta Lee, Weng, Ellen Chan three actress starred in the \"Spirit of Love\", \"Stop My Crazy Love\" and \"Dangerous Love\" three pornographic films released over the same period, the Fights naturally played very lively, Loretta Lee defeated Weng Hong, Ellen Chan, box office revenue by her starring \"Crazy Love\" and \"Love the Wizard Jieyou one thousand million down the other hand, Weng \"Crazy Love\" unstoppable received seven million, \"Dangerous Love\" is just over six million. by [lsjt.org] <br> Speaking with \"Miss Asia champion & rdquo ; the title of Weng filming three films, can be considered the many twists and turns disaster ATV she had touted, but unfortunately confined to the teen idol image difficult to develop, after some psychological torment, and finally decided to follow the example of Veronica Yip to three breakthrough , took on the producer by famous filmmakers Nanyan the unstoppable Crazy Love. \"who knows\" the unstoppable Crazy Love \"reputation is good, but mediocre box office, (lsjt.org) Weng even by the Ministry three films lost Renmei clear consciously no face to see people of Syria \"(a charity by the previous Asian sister organization) the duties of the vice president, angered parents and my brother and sister, as well as with She broke off the relationship. (l $ j¦Ó.c¨½) <br> suffered a series of blows, but it has always been stronger stubborn hard Weng has not been this depressed, but intensified, not only once again starring Nanyan Producer \"brothel twelve room \",\" cosmetic \"and three films, and was Jing appreciated took a role in\" torture chamber \"and\" Manchu the Jin Gong mystery \"two costume ***.\" Manchu Ten torture \"popular, Weng play the tragic eclectic cabbage very vivid, and has been well received. <br> in 1997, Weng wore a porn star&#39;s name to go to Taiwan, although the director Chu Yen-ping et al catch * pass * strong * \"continue to have bare performances, they discover their own comedy to., she was shot in Taiwan\" perfect match \"witty performances at the same time she was in\" The Fearless Zhong Kui \",\" Dharma strong female images and other TV shows focus on shaping the pungent popular <br> in Taiwan, Weng successfully emerge from the shadow of the three porn stars make their own acting career further development. recently, she was overcome physical illness in Taiwan, Mainland China, Hong Kong, starred in many TV series and independent RBI of his career, and even opened a partnership with lin brings economic man company operating beauty and other sideline, it seems that the pungent Asian sister really is to do a strong woman. <br>'
);

?>