<?php

/*
	englist file:1907-6-2
	create time:2013-01-01 21:02:27
*/

return array(
'title'=>'Lake uprising of the seven women in Huizhou, Guangdong',
'class'=>0,
'cont'=>'June 2, 1907 (April 22) DingWei, Huizhou, Guangdong province, seven women Lake uprising. <br> Huizhou uprising is led by League members Dengzi Yu armed insurrection against Qing rule. After the failure of the <br> Boxer Rebellion, in order to adapt to the development of the situation in China at that time, in August 1905, (而身d芋y身里h貝 $ 而身ry.c身m) bourgeois revolutionaries was established in Tokyo, Japan Modern bourgeois revolutionary party - Chinese Revolutionary Alliance (United League), as the leadership of the political parties of the national revolution. United League is made up of many of the original revolutionary groups, such as the Revive China Society, (lsjt.org) Restoration League, (lsjt.org) Hua Xing Hui, hundreds of franchisees, Sun Yat-sen was elected Prime Minister. (TodayinHistory.cn) <br> United League established in southern China launched several uprisings, they plan to Guangdong first take, and then take Guangxi gradually occupied the seven provinces in the south, and then north to the Yangtze River, anti-fire lavished National country. Planning Chaozhou uprising, in order to distract the Qing, Sun Yat-sen sent Deng Ziyu in Huizhou uprising. Deng Ziyu to operate hotel industry in Singapore, Huizhou will be the party fled to the South Seas, most of them to take refuge in him. Therefore, Deng Ziyu high prestige in societies in Huizhou. June 2, 1907, Deng Ziyu delegate Chen Chun, SUN hidden from Huizhou 20 the seven women Lake mob vertical flag uprising the Reaver Qing garrisons firearms killed Qing people, captured some Hui Village. Societies everywhere have responded to participate in the battle with the Qing. Rebel army issued a call to arms: \"lengthy Chinese emperor sway in China, thousands of state tribute nations. The barbarians accounted kill, Cihen Nanxiao. \"The rebel army come and erratic, invincible, repeatedly beat the Qing. This uprising lasted more than 10 days. Finally, because outnumbered, the rebels buried firearms to dissolve itself. After a failed uprising Dengzi Yu Hong Kong Secretary for Chinese Affairs ordered to leave the country. Leadership of another uprising, Chun Chen fled to Hong Kong, and want to switch to the Nanyang, Sun hidden by the Qing government in 1909, the Guangdong authorities killed. <br> including Huizhou and seven women Lake uprising, including United League from inception, continuous launched leadership 8 intifada, but to the broad masses of the people to do it because there is no hard and deeply mobilize and organize work, engage in purely military adventure These uprisings have ended in failure. However, each time the uprising are a heavy blow to the reactionary rule of the Qing Dynasty, and expand the political influence of the League in the masses, and inspire the people of the country&#39;s anti-emotional played a revolutionary propaganda and exciting role. <br>'
);

?>