<?php

/*
	englist file:1922-7-2
	create time:2013-01-01 23:52:08
*/

return array(
'title'=>'The Crusaders return in triumph crusade against sudden defection of Chen Chiung-ming Navy Commander',
'class'=>0,
'cont'=>'(Saigon-year leap in May eighth day), July 2, 1922, the Crusader return in triumph crusade against sudden defection of Chen Chiung-ming Navy Commander. the rate Fleet Chen Ce, <br>, leaving Whampoa In in 1922, the Northern Expedition return in triumph into Guangdong crusade against Chen Chiung-ming. Chen Chiung-ming launched an armed coup on 16 June, the domestic Burning with indignation. Sun Yat-sen in Yongfeng ship, the exercise of the powers of the presidency as usual, at the same time secretly ordered brightest Crusader back to Guangdong insurgency. Sun Yat-sen convened the a Navy Captain Description stick Whampoa reason, the captain said to obey. The same day, the Crusader return in triumph into Guangdong Army crusade by Xu Chongzhi, Li Fulin, Zhu Peide, David Huang Chen Chiung-ming, preparing to attack Shaoguan. In <br> 7, 3 to 5, 2009, Navy Commander Wen Shude twice the rate of sea-Qi, Hai Chen, Shiu, Eagle four-ship captain and followers to Yong Feng attempt to expel the Sun Yat-sen, to compel him to leave Fleet . Navy factions struggle began to intensify. Temperature second board Yong Feng Chen policy rate each owned Sun captain and officers, division of Sun Yat-sen on both sides, Chen Ce guard beside Sun Yat-sen, Zhuang owned Sun Shengwei. When the temperature threatened its \"determined to neutral, and has prepared the ceremony, farewell Sun Yat-sen\", the atmosphere suddenly tense, Chen Ce hand the a revolver pistol grip, want to pull out the disposal Wenshu De schematically stop the Sun Yat-sen. <br> in support of the naval officers, led by Chen Ce, Sun Yat-sen rage against the the Wenshu De cowardice and treachery. The Wen Shude had bitterly retreat, no longer come back. July 8, Wenshu De Chen Chiung-ming 200,000 large sums of money by suborning publicly renegade Sun Yat-sen, led sea Qi, Hai Chen, Shiu and three destroyers attached enemy. July 9, the commander of the Marines stationed at Cheung Chau Sun Xiangfu, with temperature mutiny, to meet the enemy landing, the fort thus fall in Cheung Chau. The Navy losing land barriers, with no insurance data for nine ship to get rid of the defensive situation, led by Chen Ce treasure wall, Kwong Yu Guang Zhen, Guang Geng Guang Hang, Yuen Foong, Chu Yu-Yu Zhang, dance phoenix firepower to suppress the gun attack on land, together leaving Whampoa, Send parked in new river, cover on land owned by the Sun forces retreat. <br>'
);

?>