<?php

/*
	englist file:1945-7-2
	create time:2013-01-01 23:03:54
*/

return array(
'title'=>'Sino-Soviet negotiations to discuss Soviet troops conditions',
'class'=>0,
'cont'=>'July 2, 1945 (, Yiyou May 23), the Sino-Soviet negotiations to discuss Soviet troops conditions. <br> In 1945, Soong, head of the Chinese government delegation, headed by Soong Chinese government delegation negotiating with the Soviet Union in Moscow. July 2, negotiations formally began. <br> Soviet side of Outer Mongolia independent management Dalian Port, Port Arthur loan, the superior interests of the Road, Hong Kong, (lssjt.cn) North Korea prop governance, and the Soviet Union the Covenant entered into a package of bilateral relations, the impasse in negotiations. Both sides of Yalta secret treaty interpretation differences. Soong negotiations after informed the U.S. ambassador to the Soviet Harriman hope that the U.S. side speech. U.S. Secretary of State Byrnes call back While the United States believes that the original meaning of the interpretation of the Soviet side and a secret treaty contrary interpretation of the U.S. nor China \"lead to negotiations on the Soviet Union by\". Chiang Ching-kuo approached to the will of a private citizen, with Stalin as the Soviet Union do not adhere to Outer Mongolia independent. Chiang Ching-kuo told Stalin: the eight-year war in China, in order to regain lost ground, to the sovereignty of Outer Mongolia to give up, \"will for the people not understanding. Stalin told Chiang Ching-kuo, he insisted Outer Mongolia \"independent\" to defend Siberia, As Stalin adhere, July 6, (lsjt.org) Chiang Kai-shek in Chongqing to convene senior aide to discuss countermeasures agreed to Outer Mongolia independent. July 9, in the fourth round of the Sino-Soviet talks, the Chinese side on the issue in Outer Mongolia \"quasi its independence. Intends to use the referendum to pass, announced a \"solution. <br> 7, 6, 2009, Chiang Kai-shek in the 6th indicate that Soong will solve the the three CCP issues and northeast, Xinjiang sovereign integrity as a condition of China consider the issue in Outer Mongolia. July 9, Soong again demanded that the Soviets only be spiritual and material assistance to the National Government; July 11 raised the national government to send military delegation to set up civil institutions in the Northeast progress with the Soviet guarantee northeast mastered in the National the hands of the Government. Stalin, Chiang Kai-shek&#39;s conditions, including conditions detrimental to the interests of the Communist Party of China, made a promise. In negotiations on July 9, Stalin said to Soong does not support the Chinese Communist Party, China Aid only to the central government. So that the Sino-Soviet negotiations impasse finally a turning point. <br>'
);

?>