<?php

/*
	englist file:1834-2-7
	create time:2013-01-01 20:53:26
*/

return array(
'title'=>'Periodic table discoverer of the birth of Dmitri Mendeleev',
'class'=>4,
'cont'=>'February 7, 1834 (Kimi twelfth lunar month Eve), the birth of Dmitri Mendeleev, the discoverer of the periodic table. <br> Dimitri Mendeleev&#39;s Birthday \"target =\" _blank \"> Mendeleev <br> 19th century Russian chemist, he discovered the periodic law of elements, and made the world&#39;s first periodic table. February 2, 1907, the Russian chemist who enjoys a worldwide reputation for MI, passed away, that day away from his 73-year-old birthday only six days. <br> his famous was born along with the periodic law of elements and chemical principles, in the late nineteenth century and early twentieth century, the international chemical industry as the standard works, before and after a total of eight edition, influence generation after generation of chemists. <br> Russian chemist Mendeleev (1834 to 1907), was born in Siberia and his childhood love of labor, nature lovers, study hard. <br> 1860 Mendeleev book \"Chemical Principles plagued by a lack of systematic inorganic chemistry book to consider writing plans deep So he began to collect every known element of the nature of the information and data to previous results achieved in practice, who can find are collected in together. humanity on the elements of the problem of long-term practice and awareness activities, a wealth of material he found that some elements in addition to features common on the basis of research results achieved the previous example, known halogen elements fluoro, chloro, bromo, iodo, have similar properties; alkali metal elements, lithium, sodium, potassium and exposed in the air, are soon to be oxidized, so are present in nature only in compound form; there the metal cases of copper, silver, gold can be long remain in the air without being corroded, is why they are referred to as precious metal. <br> Thus, Mendeleev began to try to arrange these elements in his each elements create a rectangular cardboard cards to write on a rectangular piece of cardboard on the element symbol, atomic weight, elements of nature and its compounds. then they row and row of nails in the wall of the laboratory after a series of after the line up, he found that the regularity of the chemical properties of the element. <br> Therefore, when someone Mendeleev&#39;s discovery of the periodic law of elements look very simple, easy to say that he is to play poker great discovery, (lsjt.org) Mendeleev was seriously replied, since he determined to engage in this exploratory work, has been spent about 20 years of effort, finally in 1869 of element periodicity He categories of chemical elements from the chaotic maze the geography out a clue, because he has a lot of courage and confidence, not afraid of the famous accusations, not afraid of ridicule, the courage to practice courage to promote their point of view, and finally has been widely recognized. <br>'
);

?>