<?php

/*
	englist file:1953-1-7
	create time:2013-01-01 20:56:33
*/

return array(
'title'=>'Truman announced that the United States has developed a hydrogen bomb',
'class'=>0,
'cont'=>'January 7, 1953 (the Imjin annual winter month 22), Truman announced that the United States has developed a hydrogen bomb. <br> developed in the United States in the 1950s, an aviation throwing hydrogen bomb-MK17 hydrogen bomb. It weighs 21 tons, the size of almost like a small locomotive. September 1949 Soviet atomic bomb experiment was a success, the United States shocked facilitate strategic considerations must create a more powerful bomb. <br> 1950, U.S. President Harry Truman decided to develop the hydrogen bomb. H-bomb research by scientists of Hungarian nationality Taylor leadership, the use of the atomic bomb to promote the high temperatures generated in the explosion, the deuterium fusion reaction. May 1951 hydrogen bomb principle test preparations sequence test bomb codenamed \"George\", in the Pacific ¶÷ÄáÍþÍÐ¿Ë Island test site. Up to 62 tons of extremely bulky test assembly was placed 60 meters of steel frame device as in liquid deuterium fusion loading and cooling system so that the deuterium in the extremely low temperatures. Experiments prove that the explosion was so much higher than the atomic bomb. Principles of <br> hydrogen bomb test success greatly advanced manufacturing real hydrogen bomb. November 1, 1952, a hydrogen bomb test device \"Mike\" in the Pacific island of ¶÷ÄáÍþÍÐ¿Ë explosion. The device is six meters high, 1.8 meters in diameter and weighs 65 tons, it looks like a big thermos bottle, the explosive power of NTN equivalent of 10 million tons. Equivalent to 500 times the Hiroshima-type atomic bombs. (L $ dj¦Ó.c¨­m) <br> \"Mike\" the volume ratio of a truck is also large, it must be equipped with a benzene weight refrigeration system, such apparatus aircraft, missiles are unable to carry, no practical value. Later, people using a lithium isotope lithium-6 and deuterium compounds-lithium deuteride as nuclear fuel. Lithium deuteride is solid, without cooling the compressed, low production cost, small size, light weight, easy to carry. This hydrogen bomb known as \"dry\" hydrogen bomb. In 1954, successfully tested a practical hydrogen bomb in the United States than the base hair island. <br> 1953, the Soviet Union announced that the hydrogen bomb test successful. Followed by the United Kingdom (May 1957), France (August 1858), also has a hydrogen bomb. December 28, 1966, China successfully conducted a hydrogen bomb principle tests succeed, September 17, 1967 by the plane dropped 300 tons of hydrogen bomb tests. <br>'
);

?>