<?php

/*
	englist file:1994-9-7
	create time:2013-01-02 00:24:46
*/

return array(
'title'=>'Photographer Wu Yinxian died in Beijing',
'class'=>3,
'cont'=>'September 7, 1994 (Awake August two days), photographer Wu Yinxian, who passed away in Beijing. Wu Yinxian, <br>, passed away in Beijing \"target =\" _blank \"> Wu Yinxian photographic masterpiece Qi Pu\" <br> the Honorary Chairman of the China Photographers Association, Honorary Chairman of the China Senior Photographers Association, cinematographer Honorary Chairman Wu Yinxian comrades illness on September 7, 1994, died in Beijing at the age of 94 years old. <br> Wu Yinxian 1900 Shuyang County, Jiangsu Province, was born in 1922, graduated from the Shanghai Art College. actively participate in his youth left-wing film movement; shooting the \"Fengyun children\", \"urban scenery\", \"Life and Death concentric\" road angel \"Chinese film in the history of the classic &#39;for the outbreak of the War of Resistance Against Japan, Wu Yinxian went to Yan&#39;an, successfully shooting the\" Southern Mud Bay \",\" Bethune \"precious documentary. <br> Wu Yinxian has always attached great importance to develop photographic talent, the war years as a revolutionary base training batch photography backbone after the founding of New China, he concurrently served as the Associate Dean of the School of the Beijing Film photography department head during the training of a large number of photographic rookie Wu Yinxian Photographic Art persistent pursuit of innovation since the founding, he shot a \"red flag spectrum\", \"Bethune doctor\" and other outstanding feature films, including \"Red Flag spectrum\" won the first session of the & ldquo ; Hundred Flowers Award for \"Best Cinematography Award. decades, he shot tens of thousands of photographs enthusiastic praise majestic scenery of the motherland, the colorful life of the people, celebrating the great achievements of socialist construction. editing Without the Communist Party, there would be no new China \"group according to the 16th National Photographic Art get special honor Wu Yinxian comrades for photography theory building made a significant contribution. since the reform and opening up, he completed photography theoretical writings of the composition \"and the dozen totaling more than a million words. <br> Wu Yinxian devotion film and photography career more than 70 years, a good reputation in more than 20 provinces and cities such as Beijing, Shanghai and the United States, France, (history today TodayOnHistory.com) Switzerland (on TodayOnHistory.com) Singapore, Brazil and other countries are organized his personal Film Festival. U.S. International Center of Photography in New York awarded him the photography meritorious certificate, Arles, France tenth ad hoc \"Wu Yinxian Month Ninth International Photography Festival, Hong Kong and Macao Photographic Society awarded him the title of\" master photographer. Wu Yinxian, <br>, passed away in Beijing \"target =\" _blank \"> Wu Yinxian photography masterpiece \"Red Flag Profile\" <br>'
);

?>