<?php

/*
	englist file:2002-3-25
	create time:2013-01-02 08:31:43
*/

return array(
'title'=>'Li Yaoqi big sentenced to death for embezzlement of state assets',
'class'=>0,
'cont'=>'March 25, 2002 (February 12), Imo, Li Yaoqi big sentenced to death for embezzlement of state assets. , <br> 2002 3 25, Hainan Haikou City Intermediate People&#39;s Court of the Hong Kong Macau International Investment (Group) Co., Ltd. the former chairman of the Hainan International Investment Group Limited Li Yaoqi former chairman of the corruption case, the first instance pronounced the verdict to embezzlement, embezzlement of public funds, owned assets crime of graft and sentenced Li Yaoqi to death, deprived of political rights for life and confiscated all his personal property. the <br> court has examined, Li Yaoqi in October 1992 to July 1997, using his office to take a variety of means, alone or together with others to commit crimes, wantonly corruption, embezzle and embezzlement of the assets of state-owned enterprises, for individual stocks, investment, profligate use, embezzlement of public funds totaling more than 6100 million, HK $ 150 million, owned assets totaling more than 410 million, misappropriation of public funds totaling HK $ 4.9 million. The court of <br> Li Yaoqi As the principal leaders of the state-owned enterprises, big embezzlement of state assets, his behavior constituted a crime of corruption, embezzlement of public funds and owned assets and the crime, and corruption is an extraordinary amount, the circumstances are especially serious, so law Li Yaoqi on corruption charges, sentenced to death, deprived of political rights for life and confiscation of all personal property; sentenced to 12 years in prison and the embezzlement of public funds; owned assets sins sentenced to four years in prison and fined 30,000 yuan ; decided to implement the death, deprived of political rights for life and confiscated all his personal property. Haikou City Intermediate People&#39;s <br> Court also judgment of the other five co-defendants: East Cham Industrial Co., Ltd. sentenced the former general manager Li Jianqiang death penalty, execution, suspended for two years deprivation of political rights for life, and impose confiscation of all personal property; sentenced the former general manager of the Hainan International Trust Investment Corporation, Vice Chairman Su Guohua 15 years in prison, their personal property confiscated 100,000 yuan; sentenced the Hainan International Trust and Investment Group Co., Ltd. original Vice Chairman Huowen Ming 13 years in prison; embezzlement owned assets crime of graft and sentenced to Hainan International Trust and Investment Group Co., the former vice chairman Zhang Chengguang 13 years imprisonment, confiscation of personal property 80,000 yuan ; sentenced assets owned sin the former Hainan, Hong Kong and Macao Industrial Co., Ltd., general manager of Pan Maoliang to three years imprisonment and fined 20,000 yuan. (TodayinHistory.cn) <br>'
);

?>