<?php

/*
	englist file:1961-12-11
	create time:2013-01-02 02:49:02
*/

return array(
'title'=>'Tang Dynasty Chang&#39;an City ruins uncovered',
'class'=>0,
'cont'=>'December 11, 1961 (1901 winter in early four) Tang Dynasty Chang&#39;an city site was uncovered. In In 1961, more than a thousand years ago, a metropolis of a million of our sites are uncovered. This metropolis is the famous Tang Dynasty Kyoto Chang&#39;an. <br> city covers today&#39;s Xi&#39;an city and suburban. The late Tang Bingluan, it was destroyed badly, has finally become ruins. Before the liberation, many scholars have tried to explore the ruins of this Chinatown, did not succeed due to suffer conditions. In 1957, the Institute of Archaeology of the Chinese Academy of Sciences organization dedicated Chinatown excavation team began a large-scale excavation work. After more than four years of hard work, an overview of the site has been revealed. From the ruins in the layout of the city has been excavated, palaces, streets, Square, one can imagine a busy one thousand million, when the city was grand. <br> excavation survey results prove that: Tang Dynasty Chang&#39;an City around more than 70 years, than today&#39;s Xi&#39;an old city (ie, the Ming and Qing dynasties, Xi&#39;an city was) more than five times larger. The city is divided into three parts, the the outermost outer city, the northern part of the middle is the Imperial, the Imperial City, the northern end of the center is Miyagi - Emperor place to live. On outer Guo city wall with twelve gates, has unearthed eight gates of the base address. Many aspect of the streets of the city outside the Imperial City and Miyagi neatly divided into one hundred and eight rectangular Square. <br> found has uncovered West North Avenue sites on both sides of the the intensive building base address. Many wall base is closely linked between every two houses have brick sewer, straight-through roadside ditches, there are stoves and water wells in the ruins, and the Tang Dynasty brick, fragments of pottery vessels and stone the remnants of the cattle, lions, statues and other ornaments. the <br> archaeological excavation team the Daming Palace as the focus of the excavations. Now they have the range and distribution of the Daming Palace investigation clearly exhumed five gates and city walls, two large palaces - Linde temple and Yuan Temple, and intrauterine Rendezvous pavilions, ponds, canals and other Many building sites. Entire Daming Palace ruins the range of about 15 square miles, than the Forbidden City in Beijing to be twice as large. Linde temple is one of the largest hall in the Daming Palace, constructed in rammed earth wall on the platform above. The hall Zhuchu there are more than one hundred visible grand scale. Daming Palace ruins, archaeologists also found a large number of fine tile and building stone carvings. Daming Palace building architectural art of working people has reached a very high level. (1 $ dj¦Ó.c¨­m) <br>'
);

?>