<?php

/*
	englist file:1996-8-11
	create time:2013-01-02 00:35:07
*/

return array(
'title'=>'A water level of the Three Gorges Reservoir Area immigrant work started',
'class'=>0,
'cont'=>'August 11, 1996 (Rat-June 27), a water level of the Three Gorges Reservoir Area immigrant work started. <br> ensure Jiangshun Li closure of the Three Gorges Project in 1997, a water level of the Three Gorges Reservoir Area in Sichuan Province immigrant resettlement work has recently started. damming the river <br> Three Gorges Dam Project will be the end of 1997, Sichuan Province, Wushan, Fengjie, Yunyang is the first phase of the water level submerged County, 31 towns, 165 enterprises require relocation, three county part drowned, need 22,432 people in cities and towns and rural migrants. <br> from the past in order to ensure immigrants moved to come, stability is maintained, the production of the immigrants have the money, life protection, three counties in the relocation and resettlement guiding ideology to achieve the transformation of the above aspects: rural resettlement on emphasis on the resettlement of the secondary and tertiary industries to the large agriculture-based, multi-channel, multi-form placement up; towns, factories and special facilities relocation, by the blind setting up shops in the past, to expand the scale of Go focused, concentrated into focus on efficiency up; want to invest in the use of funds from a simple blind contention indicators go to the lump sum to use, save money up. <br> It is understood that the three counties of 22,432 rural migrants have lost their land, has arranged for the implementation of land development, the swap land resettlement number accounted for 54.75%; placement number of the development of secondary and tertiary industries accounted for 28.47%; recruitment, admissions, relocation number and self-employment accounted for 6.66%, and accounted for 10.12% of the number of old-age insurance. <br> Currently, Wushan, Yunyang, Fengjie are speeding up the construction of urban infrastructure, the move to create the conditions for the large-scale immigration. Three county new site and relocation market towns everywhere in a tight construction, busy. New Yunyang county is still on the Yangtze River, is the county seat relocation farthest in the three counties, more than 30 kilometers away from the flooded the old town, the new city has been built to house 130,000 square meters; most flooded the relocation of enterprises also selected a new site to begin for the construction of the new plant. <br>'
);

?>