<?php

/*
	englist file:1984-1-1
	create time:2013-01-01 18:36:38
*/

return array(
'title'=>'The establishment of the Industrial and Commercial Bank of China',
'class'=>0,
'cont'=>'January 1, 1984 (Guihai the winter months&#39;s Eve), the Industrial and Commercial Bank of China was established. <br> 1978, the Third Plenary Session of the Eleventh Central Committee of the party held, made a strategic decision to shift the focus of the party&#39;s work to socialist modernization. Since 1979, institutional mechanisms, to break the pattern of the \"grand unification\" of the People&#39;s Bank. Agricultural Bank of China, Bank of China, the Chinese People&#39;s Construction Bank (after China Construction Bank) has divided from the People&#39;s Bank of China and the Ministry of Finance. In September 1983, the State Council decided that the People&#39;s Bank of China, specializes in the exercise of the functions of the central bank, clearly stipulates that the People&#39;s Bank of China is China&#39;s central bank, the implementation of the supervision and management of its financial sector. At the same time, the State Council decided to set up the Industrial and Commercial Bank of China. Formerly handled by the People&#39;s Bank of China Industrial and Commercial credit and savings business, borne by the Industrial and Commercial Bank of China. Reference 1 January 1984, the Industrial and Commercial Bank of China was established. <br> ICBC is the largest commercial bank in China. Through reform and development in recent years, ICBC has entered the track of quality and efficiency, and the coordinated development of the scale, the end of the end of 2002, total assets of 4.8 trillion yuan, accounting for a quarter of the sum of the domestic assets of commercial banks in China in 2002 create operating profit of 44.9 billion yuan. Industrial and Commercial Bank of China has the largest customer base in China, about 100 million individual customers and 8.1 million corporate customers, full line of over 22,000 branches and more than 40 million employees provide quality and efficient services to customers. <br> Commercial Bank of China business a wide range of business volume. The end of 2002, becoming the only one deposit balance exceeded 4 trillion of bank loan balance of nearly 3 trillion yuan. The Industrial and Commercial Bank of RMB settlement market share of 45% the liquidation share in securities, futures market remains more than 50%, in 2002 handled 100 trillion yuan RMB settlement business. <br> Commercial Bank of China with the international advanced level of computer network and technology platform. Industrial and Commercial Bank of China is a large international bank. Has 71 branches and holding bank in the world&#39;s major international financial center, and its overseas correspondent banks in late 2002 of 1020. Industrial and Commercial Bank of China in the end of 2002 the total assets of 49.9 billion U.S. dollars of foreign exchange, the annual international business settlement amount of $ 118.6 billion. (Lsjt.org) <br>'
);

?>