<?php

/*
	englist file:«∞154-m-d
	create time:2013-01-02 06:54:20
*/

return array(
'title'=>'Han Emperor Jing of China during the outbreak of the Rebellion of the seven countries',
'class'=>0,
'cont'=>'Jan. 17 -154 years (““”œ years 30 winter months), the Chinese Han emperor during the outbreak of the Rebellion of the seven countries. 514 BC, <br> <br>, January 17 (since 2526), &#8203;&#8203;the Chinese Han emperor during the outbreak of the Rebellion of the seven countries. <br> Wu Chu \"chaos\" of the seven countries in the kings joint rebellion led by Liu Bang, the nephew of the king of Wu Liu Bi launched. The seven countries involved in the rebellion king is king Liu Bi, in Chu Liu amyl, zhaowang Liu then, of Jinan Wang Liu Pi light, Zichuan Wang Xian, the glue Xiwang Liu Aung, Jiaodong Wang Liu Xiong drainage. King Liu Bi as the mastermind of the rebellion. Liu Bi premeditated the rebellion too long. This turmoil sparked by the Han emperor three years (BC 154), the Jingdi and Chao Cuo king Liu Bi guilty and want to take the opportunity to cut his Hueiji Yuzhang two county. Liu Bi took the opportunity to collude Chu, Zhao, glue the West, Jiaodong? Sichuan, Jinan Princes of the six countries launched a joint rebellion. Liu Bi-fat, two hundred thousand soldiers, known as the five hundred thousand, as the main force. Sent the Huns, East more aristocratic Minyue collusion with the name of \"The fulfillment of the punish Chao Cuo\", Jubing westward. The rebels hit Henan eastern. Kill the emperor very terrified start Yuan Ang Yee Chao Cuo, would like to meet them \"The fulfillment of the requirements in exchange for their retreat, but Chao Cuo dead rebels reclaim also publicly threatened to seize the throne. Rebels to Leung Kwok (this rule Shangqiu, Henan), the younger brother of Emperor Jing King of Liang Wu-resistance. At this time, the emperor was determined to suppress it by force. The he ordered Qiu bar Hou Having submitted the generals Dou Ying rate thirty-six generals, rebels cut off the grain Road to Jones, only with a time of 10 months, the big break rebels. Liu Bi fled Dongou for Dongou king killed. The remaining six kings are all committed suicide, seven countries have been abolished. Share This is 154 years BC, a rebellion, mutiny total of seven vassal state, it is called \"the chaos of the seven countries. CAUSE are the local Kingdom forces and contradictions of centralization, as well as the then Queen - Empress autocratic reasons. Han Jing Di pacification of the Kingdom of the rebellion, has laid a good foundation for the Later Han Wudi to continue to clear the local forces of the Kingdom. (1 $ dj¶”.c®≠m) <br> seven countries Rebellion reaction contradiction between the central and local governments of the ancient Chinese feudal society, the seven countries the chaos the Pingding marks Kingdom forces threat basic clear, greatly strengthening the centralization of the Han dynasty, to consolidate national reunification, and also to some extent the often promote the socio-economic recovery and development. (On www.TodayOnHistory.com) <br>'
);

?>