<?php

/*
	englist file:1906-10-22
	create time:2013-01-02 01:25:10
*/

return array(
'title'=>'French painter Paul Cezanne&#39;s death',
'class'=>3,
'cont'=>'October 22, 1906 (, Heigo September fifth day), French painter Cezanne&#39;s death. Cezanne <br> is known as \"the father of modern painting, in the lifetime of his life in humiliation and reviled moderate over. But he once did not compromise, and finally achieved a huge success, and also a rare example of this in the history of art. <br> Paul Cezanne was born in 1839, not far from Marseille, Aix father hat factory owner, and later became a banker. Cezanne was a child like drawing, once his paintings won second prize in the school. Father not only joy, also worried Cezanne said: \"Young people think it! \"He even exclaimed:\" genius is often a dead end, the rich talent I could survive! \"He wants his son when a lawyer to make money, at least have to be a businessman. He Cezanne sent to law school, but Cezanne do not want to be a lawyer, he forced his son to the bank behind the counter, afterwards, to pay all these efforts are in vain. Cezanne 24, he finally decided to go ascertain the Academy of Fine Arts, who knows no comprehensive examinations, the College examiner that he did not train the future. But this does not make him frustrated, he lived in Paris, to continue to study art, work hard, and sometimes even a few days do not wash. However, his return is still fail. He was 27 years old, to send a picture to the Paris Salon, did not even reply. Even the closest friends Zola has listed him as a typical written novels failed, which made him very angry, and he resolved to leave Paris. <br> 1897, Cezanne to return home and live like a hermit&#39;s life. All day instead of going out sketching needs sitting in front of a still life observation, contemplation, and very little contact with the outside world. He patiently and warmly pursuit of real, lasting, eternal things, the inner life of things and the internal structure, shape and color combination of painstaking research. Each of his next record should reconsider, his hands trembling, has been trembling to finally write so far. His efforts, however, are still not social attention, one also can not sell his paintings. Even him a picture sent to an acquaintance, himself, had pre timidly said: \"Of course, I do not want you to go home Painting with. \"What a mournful! <br> Suddenly, Cezanne painting sales, the young generation of artists in Paris, to the pursuit of novelty, inspiration in the works of Cezanne intricacies, so what becomes \"genius\" Cezanne \"The Prophet.\" Cezanne paintings value of the daughter, an eccentric old man sold the Cezanne as to express friendly gave him a small painting and live a retirement life, rely Maihua obtained. Cezanne&#39;s paintings have an enormous impact on Western European art of the 20th century, is universally recognized as the maestro. October 22, 1906, Cezanne&#39;s death. His life to the pursuit of the spirit of the art undertakings, always worth admiration. <br>'
);

?>