<?php

/*
	englist file:1983-12-22
	create time:2013-01-02 02:26:37
*/

return array(
'title'=>'The successful development of our first billion computer &quot;Galaxy&quot;',
'class'=>0,
'cont'=>'December 22, 1983 (Guihai the winter months XIX), China&#39;s first billion computer \"Galaxy\" was successfully developed. <br> 1983 to December 22, 2011, up to more than 100 million times per second operator of China&#39;s first computer - \"Galaxy\" was successfully developed in Changsha. <br> \"Galaxy\" giant computer system is the fastest, the storage capacity of the largest, most powerful computer. Petroleum, geological exploration, medium-and long-term numerical forecast, satellite image processing, an important means of calculation of the large-scale scientific research topics and national defense construction, has a very important role to accelerate the modernization of our country. <br> Currently, only a few countries able to develop the giant computer. \"Galaxy\" The successful development of the computer, two years ahead to achieve the goals of the National Science Conference 1985 ultra-high-speed supercomputers will be put into use, \"China has stepped into the ranks of the world developed supercomputer countries indicates that the development of China&#39;s computer technology to a new stage. Since May 1983, the Leading Group of the State Council computer LSI 95 of the 29 units of computer experts and engineering and technical personnel, the establishment of the \"Galaxy Computer national technical appraisal group and divided into seven groups of & ldquo the machine; Galaxy comprehensive, rigorous assessment of technical. The results showed that: 26 the correctness exam with wide representation in the national economic development and scientific research, has calculated three times, exactly the same data, the result is correct, accuracy to meet the requirements; operating system single-channel or multi-channel operation system control reliable, system-wide, and host; hardware system the vector computing speed reached more than 100 million per second, the software system is rich in content, more powerful, easy to use, state-of-the-art performance, \"Galaxy\" supercomputer in the design, production and commissioning process proposed many new technologies, new processes and theoretical issues. Some is used for the first time, and some reached the international level. (L $ dj¦Ó.c¨­m) <br> \"Galaxy\" supercomputer research task by Comrade Deng Xiaoping to the National Defense Science and Technology Commission in February 1978, took this task to implement the National Defense Science and Technology, National University of Defense Technology computer Institute. Institute of only 200 people, the staff team is very young, and very few have the technical staff of professors and associate professors, but these young people to carry forward the self-reliance and hard work of the spirit, to rely on the support of more than 20 units around collaboration, only 5 years time, to complete the work on the development of the \"Galaxy\" supercomputer, whom the people of the country and elated. <br>'
);

?>