<?php

/*
	englist file:2003-4-29
	create time:2013-01-01 21:46:56
*/

return array(
'title'=>'Hebei Province Cong Fukui, former executive vice governor sentenced to death for accepting bribes',
'class'=>3,
'cont'=>'April 29, 2003 March 28 (¹ïÎ´ years), the former executive vice governor of Hebei Province Cong Fukui sentenced to death for accepting bribes. <br> 2003 4 29, the Intermediate People&#39;s Court of Zhangjiakou City, Hebei Province, according to the Hebei Provincial Higher People&#39;s Court to specify the jurisdiction of the decision to make the sentence had been passed in accordance with the law, the former executive vice governor of Hebei Province Cong Fukui bribery case, Cong Fukui sentenced for taking bribes was sentenced to death for accepting bribes \"target =\" _blank \"> Cong Fukui death penalty, execution, suspended for two years deprivation of political rights for life and confiscation of all personal property <br> Court has examined, from July 1997 to 2000 month, Cong Fukui as the Standing Committee of the Hebei Provincial Party Committee, during the executive vice governor of the People&#39;s Government of Hebei Province, the use of his office, in Hong Kong Sheng Kangguo occasion to apply for loan extension Ltd. Hebei International Trust and Investment Corporation, the transfer of the Hong Kong Sheng Kangguo International Limited in shares of Sheng the Cang Development Co., Ltd., Hebei Yutong Industrial Co., Ltd. to China Construction Bank Hebei Branch of loans Qin Longguo interpersonal Industrial Co., Ltd., Qinhuangdao City, Qinhuangdao City Waterfront the forest contract fee disputes, [l $ dj¦Ó.¨­r¨À] China Heilongjiang International Economic and Technical Cooperation to apply to the Agricultural Bank of China Hebei Branch the equipment advance payment bond, Shenzhen North thing Investments Limited Hebei promote automobile exhaust purification device matters, to seek benefits for Cong true, CP patients. OF THE FOURTH MILITARY, Li Xiaoming, Wang Xiaoguang obtain the 4 people illegally accepting money from a total of RMB 936 million yuan. <br> Zhangjiakou City Intermediate People&#39;s Court that the Cong Fukui, as national staff, used his position to accept the trust of others, for the benefit of others, obtained from illegally accepting other people&#39;s property, his behavior constituted the crime of accepting bribes, the circumstances are especially serious, because of the huge amount of bribes, upon complaint should be sentenced to death, but in view of its justice, a good attitude, and can take the initiative to confess some of the facts of the crime and the alleged stolen money has been recovered and the other case the plot, and the imposition of the death penalty, do not executed immediately. therefore made the decision in accordance with the law. <br>'
);

?>