<?php

/*
	englist file:1935-5-29
	create time:2013-01-01 21:34:56
*/

return array(
'title'=>'Central Red Army force a crossing the Dadu',
'class'=>0,
'cont'=>'May 29, 1935 (April 27), seeing in the Central Red Army force a crossing the Dadu River. <br> Luding tiesuoqiao <br> May 15, Chiang Kai-shek appointed Ren Chuanjun twenty-Corps YEUNG Sum as Dadu garrison command, led his troops from southern Sichuan speed rushed Dadu arming. And adjust the twenty-first, the Fourth Army, each one under their command. on <br> 16, Chiang Kai-shek make Kang border guards commander and the Twenty-Fourth Army commander Liu Wenhui January completed Ya River, Dadu coastal bunker build. 18, and let them ChuanJun brightest \"strict precautions against the schemes of the Central Red Army and the Red Fourth Army partnership to achieve.\" In May 25, 2009, the Central Red Army force a crossing the Dadu River. 24, 2009, the Central Red Army captured Dadu the right bank the Shimian anshun field, even annihilate the enemy troops two. The next day, even 17 soldiers of the first battalion of the first regiment of the Red Army led by the company commander Xiongshang Lin, take a boat braved heavy enemy fire, force a success, rout a battalion of the left bank of the enemy garrison. The Dadu fast-flowing, you can not bridge, only four boats, only a day crossing a group. Central Military Commission decided to seize the upstream Luding bridge to cross the river, the deployment of the first division and cadres of the Red Army group owned by Nie, Liu Bocheng command, follow the left bank of the Dadu River of Lin Biao and the rate of the main and the Fifth Army regiment of the Red Army headquarters, the second division follow of the right bank of the Dadu River, Luding Bridge radical, collaborative Xiqu bridge. the <br> 5 29, the fourth group of the second division of the Red Army defeated the Kuomintang army blocking the forced march of 120 kilometers a day and night, to seize the Luding Bridge western end of the bridgehead. At this time, wood tiesuoqiao has all been removed only a few root iron chain dangling in the air, the east coast of the bridgehead Sichuan army about a group relying on fortifications resistance forces, the Red Army Second Division with 22 soldiers in the company commander Liao large beads led intensive fire, braving enemy, climbing leaning vacant iron chain forward attack to Qiaodong, captured the head of the East bridgehead. Followed by the bridge, follow-on forces occupied Luding city, the north and the left bank of the Red Division rendezvous. <br> anshunchang ferry <br>'
);

?>