<?php

/*
	englist file:2007-6-29
	create time:2013-01-02 00:15:18
*/

return array(
'title'=>'Congress passed the &quot;Labor Contract Law of the People&#39;s Republic of China&quot;',
'class'=>0,
'cont'=>'June 29, 2007 (May 15), Chinese New Year, the National People&#39;s Congress passed the \"Labor Contract Law of the People&#39;s Republic of China. <br> 2007 06 29 twenty-eighth session of the Tenth National People&#39;s Congress Standing Committee passed the \"Labor Contract Law of the People&#39;s Republic of China, with effect from January 1, 2008 implementation. <br> the People&#39;s Republic of China, in June 1950, the Central People&#39;s Government announced the Trade Union Law of the People&#39;s Republic of China \", the same year, the Ministry of Labor announced the\" Provisions on the labor dispute settlement procedures, in February 1951, the State Council announced menstruation Labor Insurance Regulations of the People&#39;s Republic of China \"(1953 re-released) as amended in August 1952, the Government Administration Council issued decisions on labor and employment issues. In July 1954, the State Council announced the \"state-owned enterprise internal labor rules Outline, in June 1956, the State Council announced the decision on wage reform in 1956, the State Council announced the plant safety and health regulation, construction and installation engineering safety technical regulations.\" and the workers staff casualties reporting procedures. <br> 1956, China has drafted the \"Labor Law\" Due to historical reasons, the abortive. 1979 second drafting of the \"Labor Law\", in July 1983 by the State Council executive meeting to discuss the draft, but a lot of the problem is difficult to properly resolve, not submitted to the National People&#39;s Congress. Third drafting of the early 1990s, the Labor Law, the Standing Committee adopted on July 5, 1994. \"Labor Law of the People&#39;s Republic of China\" promulgated mark Labor Law in China entered a new historical stage. 13 Chapter 107 of the labor law, including general principles; employment promotion; labor contracts and collective contracts; work time and rest time; wages; labor safety and hygiene; special protection of women and juvenile workers; vocational training; social insurance and welfare ; labor dispute; supervision and inspection; liability; Annex. \"Labor Law\" is the Basic Law, which laid the foundation for labor legislation. \"Labor Law\" legislation guiding ideology is: (1) fully reflects the constitutional principles, highlighting the protection of the rights and interests of laborers. (2) help to promote the development of productive forces. (3) lay down uniform standards and norms. The ¢Ü adhere to proceed from China&#39;s national conditions, as far as possible with the international practice. This guiding ideology to ensure the formulation of the \"Labor Law\" with Chinese socialist characteristics. <br> new law one to bid farewell to the era of low labor costs to the community, which has caused a lot of discussion within the community, but for now, the enforcement of labor law is not enough, new hair content is also very difficult to achieve! <br>'
);

?>