<?php

/*
	englist file:1904-9-29
	create time:2013-01-02 01:05:59
*/

return array(
'title'=>'Physiologist and expert haematologists easy to see the dragon born',
'class'=>4,
'cont'=>'(Jiachen August 20), September 29, 1904, physiologist and expert haematologists easy to see the dragon born. <br> <br> easy to see the dragon, Ranking formerly known as A ball, was born on September 29, 1904 (Lunar Jiachen Aug. 20) (this is a rural Xiangyin County, Hunan Province Miluo County). The date of his birth coincided Mid-Autumn Festival shortly after. Folk people in his hometown to celebrate the Mid-Autumn Festival dragon dance. Seen before birth to him in front of the house of his mother was in the dragon dance, give him the \"Dragon\" a. Later, he liked the name, going to school and has been using the name of \"Dragon\". 1918 to ideological access to 1922 study period Yali Middle School in Changsha the introduced foreign scientists deeds readings, made a deep impression, buried in the depths of the soul to learn sages, learning science, for the benefit of mankind. To university, his sister suffering from meningitis died, are determined to study medicine. 1923 was admitted to the long Xiangya premed undergraduate in 1925. A time when the warlord era of 1926 Xiangya Medical College, was forced to close down, is to transfer to Wuchang Zhongshan University School of Medicine. Revolution, the rapid development of the situation, and join the army, in 1927, decided to participate in the Northern Expedition. Editorial Unit in Wuhan Northern Expeditionary Army General Political Department Publicity Division lieutenant propagandists. After the coup of April 12, the Wuhan National Government to follow Chiang Kai-shek&#39;s anti-communist, is easy to see the dragon then leave Fanxiang, then to Guangzhou applying for the Dongshan Army hospital pharmacy any pharmacist. National Shanghai Medical College, in 1928, re-enrollment. Are class of 1933 graduate, a five-year academic distinction from Gold Medal. After graduating with Cai Qiao went to Shanghai Lester Institute of Medicine (Henry Lester Institute) any researchers to study the role of the liver to maintain blood glucose concentration, etc., five papers. He could not bear the physiological British leaders of the scientific group BEReid Chinese researchers discrimination, exclusion, angrily leaving in 1935, with Cai Qiao had just set up shortly, equipment, condition, treatment much worse Nanjing Central University School of Medicine any Lecturer of physiology Branch. He has published many articles in the Chinese Journal of Physiology (the English version of the Chinese Journal of Physiology) in cooperation with Cai Qiao. <br> Comments: the founder of transfusion Ambulance career, (Lssdjt.com), founder of the modern blood bank <br>'
);

?>