<?php

/*
	englist file:1984-10-20
	create time:2013-01-02 01:33:37
*/

return array(
'title'=>'The Third Plenary Session of the Twelfth Central Committee of the Communist Party decided to reform of the economic system',
'class'=>0,
'cont'=>'(On September 26 JiaZi), October 20, 1984, the Third Plenary Session of the Twelfth Central Committee of the Communist Party decided to reform of the economic system. <br> Plenary venue <br> 1984 on October 20, 2009, the Third Plenary Session of the Twelfth Central Committee of the Communist Party in Beijing. The Plenary analyze China&#39;s current economic and political situation, summed up China&#39;s socialist construction of both positive and negative aspects of the experience. Agreed that: must be in accordance with the basic principles of Marxism with China&#39;s realities, and building socialism with Chinese characteristics, the general requirements, further invigorating the domestic economy, external implementation of the principle of open implementation to speed up the entire city as a focus of economic system reform pace, in order to facilitate better and create a new situation in the socialist modernization drive. Plenary unanimously adopted the decision of the CPC Central Committee on the reform of the economic system. \"Decision\" is divided into 10 parts: a reform our situation is an urgent need for the development; reform to create a vibrant socialist economic system; enhance the vitality of enterprises is the central link of economic reform; Fourth, the establishment the implementation of the government and enterprises segregation of duties, play to the functions of government agencies to manage the economy properly; consciously apply the law of value of the planned system, the development of the socialist commodity economy; establish a reasonable price system, pay full attention to the economic levers; six, seven, establish more forms of economic responsibility, earnestly implement the principle of distribution according to work; eight actively developing various economic forms, further expansion of foreign and domestic economic and technological exchanges; nine, only use a new generation, creating a socialist economic management cadres grand team; ten, to strengthen the party&#39;s leadership, to ensure the smooth progress of reform. The plenary session also discussed and adopted at the Third Plenary Session of the 12th Central Committee of the Communist Party of China&#39;s decision on the convening of the meeting of the representatives of the party&#39;s national. <br> Plenary decided the party&#39;s national congress was held in September 1985, meeting two issues: discussion and adoption of the National Economic and Social Development Seventh Five-Year Plan and recommendations; co-opted member of the Central Committee of the Organization matters. The decision <br> (Lssdjt.com) <br> <br> \"People&#39;s Daily\" published'
);

?>