<?php

/*
	englist file:1983-12-15
	create time:2013-01-02 02:01:56
*/

return array(
'title'=>'The establishment of the Chinese women&#39;s football team',
'class'=>0,
'cont'=>'December 15, 1983 (Guihai winter of January 12), the Chinese women&#39;s soccer team was established. <br> 1983 12 15, the establishment of the Chinese women&#39;s soccer team \"target =\" _blank \"> China women&#39;s soccer team was formally established. has a long history of women&#39;s football, that is painted on the two years of the Eastern Han Dynasty, Henan Songshan Zhongyue Que vivid woman playing soccer murals. Tang and the Five Dynasties, the Women&#39;s game has become increasingly common, then the front of the hall laying both sides of the floor, cold house people step to play ....... \"Poems and. Northern Song Dynasty The women&#39;s football is more vigorous, the current collection of Song dynasty pattern bronze mirrors, lifelike record then women&#39;s football scene. <br> earliest modern women&#39;s football in our appearances in the 1920s, when Shanghai appear first support women&#39;s soccer team. they often Shanghai South Stadium and East Asia Sports College men&#39;s team contest. Unfortunately trainees after graduation, this football team disbanded following the late 1950s, Guangdong Meixian was once the five female football team. <br> potential of the Chinese women&#39;s football in the late 1970s began to be uncovered. 1978 Women&#39;s spark ignited in Yunnan, Shaanxi, Liaoning and other places first, followed by the rapid expansion of throughout the country in 1981, in Chuxiong organized the first national women&#39;s soccer game. country&#39;s 10 provinces and cities in the Women&#39;s Football Tournament was held in Beijing in 1982, the national women&#39;s soccer team this year has reached 27, and the following year the competition jumped to 35 teams, almost all provinces, municipalities and autonomous regions in key areas have their own women&#39;s football team in 1987, women&#39;s football, with its extensive mass foundation and potential, was officially listed as the sixth National Games event (on com) <br> China Women&#39;s exchanges with foreign countries, began in 1983, this year, the first held in Guangzhou International Women&#39;s Invitational, Japan, Singapore and China, six teams participated in 1984 years, Xi&#39;an was held in Europe, America, Oceania champion, and Japan, China to participate in international competitions. strong teams with foreign exchange, the Chinese team&#39;s technical level has been markedly improved. between July and August 1986, the Chinese women&#39;s soccer team expedition to Italy, has achieved good results of the third and first in December of the same year, the Chinese women&#39;s football full game without losing a ball recording won the Sixth Asian Cup Women&#39;s Soccer Championship, the desire out of Asia, for commemorate this historic victory, the National Sports Commission granted the title of \"China&#39;s first batch of female soccer athlete of the national women&#39;s football team then. l $ j¦Ó.c¨½] <br>'
);

?>