<?php

/*
	englist file:1980-4-15
	create time:2013-01-01 21:46:42
*/

return array(
'title'=>'Famous French writer Jean-Paul Sartre&#39;s death',
'class'=>3,
'cont'=>'(Gengshen March day), April 15, 1980, the famous French writer Jean-Paul Sartre&#39;s death. <br> 1980 to April 15, 2011, Paris mourning philosopher Jean-Paul Sartre&#39;s death, at the age of 74 years. He left his lover, 50 years knowledge debate Yameng Na - Deborah Preval, leaving a large number of novels and other prose works, including the monograph \"Being and Nothingness\" s stirring drama \"There is no way out. \" <br> Sartre was born in a fact never appreciated his talent bourgeois family. Not yet reached the 4-year-old, he began reading. Small when he finds the word is \"the essence of things, (history TodayOnHistory.com) the age of 60 participate in the May 1968 street protests became a Marxist. He later point change. Obligations should be action \", he said,\" rather than with words. <br> 1933 he was studying philosophy under the guidance of Martin - Heidegger. Martin - Heidegger broaden the perspective of his presence and awareness. Sartre, in turn, asked his readers to decide for themselves, asking them to liberate itself from the expectations of others really feel own existence. the <br> Sartre&#39;s life never shies away from reality, but also full of militancy. This attitude can be seen as speech barrels of gasoline standing on the side of the road (rather than sitting on the couch) in the performance of his usual attitude towards life. <br> 1961 Nobel Prize for Literature vacancy. The honor of the Swedish Academy was originally intended to award to 50-year-old French existentialist philosopher, novelist, playwright Sartre (1905-1980), but the maestro refused to accept this honor. In a letter addressed to the Swedish Academy, he stated the reason, he said that his conduct was not for the Nobel Prize, but he did not receive any awards from official agencies issued. Sartre objective reason, he thinks that in the field of culture, the struggle of the East and West, eastern and western culture is in fact peaceful coexistence. He realized that the phenomenon of cultural contact in some cases there will be conflict, to exclude these conflicts must rely on the human and cultural contact, can not rely solely on the good offices of a number of institutions. The same time, he also declared that he is posed by the conflict of two cultures, but his compassion is no doubt that standing on the side of socialism. the Paris street <br> packed masses of mast <br>'
);

?>