<?php

/*
	englist file:1934-7-15
	create time:2013-01-01 23:03:17
*/

return array(
'title'=>'Red Army northward advance team composed',
'class'=>0,
'cont'=>'(Awake of June fourth day), July 15, 1934, the Red Army the northward advance team composition. Central workers and peasants <br> democratic government and the Chinese Workers &#39;and Peasants&#39; Red Army Revolutionary Military Committee for the Red Army northward anti-Japanese Declaration issued <br> in the beginning of July 1934, the CPC Central Committee in order to oppose the Japanese imperialist aggression, breaking the KMT Central Soviet Area \"encirclement and suppression\" decided anti-Japanese Red Army Red Army advance team, Huai Island any Army chief Le Shaohua any political commissar. The red seven Regiment was ordered to be transferred back from the Fujian Liancheng Ruijin. <br> 7, the 7th Regiment under the escort of nine Army from Ruijin Qingliu, Wing, captured by changting, Daejeon, the red seven Army was formally announced foreign northward anti-Japanese \"Red Army activities in the name of the advance team. <br> 7 May 15, the central government and the Chinese Workers &#39;and Peasants&#39; Red Army of the Chinese Soviet Republic Revolutionary Military Commission issued northward for the Chinese Workers &#39;and Peasants&#39; Red Army anti-Japanese Declaration proclaims sending anti-Japanese advance team northward anti-Japanese action, said \" The anti-Japanese Red Army northward advance team is willing to work together with all the Chinese people to the national revolutionary war, Down with Japanese imperialism \". <br> declaration also proposes five specific claims: betrayed by the Kuomintang government resolutely opposes territorial sovereignty, against the \"Direct negotiations\", against the recognition of the puppet state of Manchukuo; \"Dear John\" immediately announced to Japan (history Today com) announced that all Sino-Japanese treaties and agreements invalid, the mobilization of the national army, navy, air force war against Japan; armed people across the country, the organization Volunteer with the guerrillas, directly involved in the Sino-Japanese War, anti-Japanese advance actively support the Northeast Volunteers and the Workers &#39;and Peasants&#39; Red Army northward team; confiscated all the property of the Japanese invaders and traitors, to stop paying the principal and interest of all government bonds paragraph; universal organization people in the anti-Japanese groups, \"absorb the majority of the masses, of all ages, religious beliefs, political affiliation to the anti-Japanese groups in the past. \" <br>'
);

?>