<?php

/*
	englist file:1909-9-15
	create time:2013-01-02 01:02:52
*/

return array(
'title'=>'International geneticists, China, one of the founders of modern genetics Tan Jiazhen birth',
'class'=>4,
'cont'=>'(Jiyou August two days), September 15, 1909, the International geneticist Tan Jiazhen of modern genetics, one of the founders of birth. <br> on the Jiazhen birth \"target =\" _blank \"> Tan Jiazhen, international geneticists, one of the founders of modern genetics, distinguished scientist and educator. Ningbo, Zhejiang Province in 1909 Cixi, Ningbo, Zhejiang County. born September 15 1930 Soochow University, Bachelor of Science, 1932, Yenching University M.Sc. in Drosophila evolutionary genetics research in T. Dobrzanski Professor, guidance in 1934 , using the latest methods for the study of Drosophila salivary gland chromosomes, chromosomal differences between closely related species of Drosophila and the genetic map of chromosome, and promote the formation of the \"modern theory of evolution. while working in the United States, has alone or with The scientists from the United States, Germany and other countries to cooperate and published more than 10 papers. stain mosaic dominant genetic phenomenon, subject to the attention of the international genetics community. 1936 by the California Institute of Technology Ph.D. 1946, found in the Asian Harmonia axyridis. (1937) after returning Kezhen principals invited any Zhejiang University, Professor, Department of Biology, Faculty of Science Dean <br> 1952 he was appointed Professor and Chair of the Department of Biology, Fudan University, established the nation&#39;s first genetics professional, served as Biology Department, director of the Institute of Genetics, Vice-Chancellor, Dean of the School of Life Sciences, and other staff. since 1978, has initiated and served as vice president of the Genetics Society of China, president and honorary president, editor of Genetics, Chinese environmental lure Society, chairman of the change agent and Biological Engineering Society in 1983, he was appointed Fudan consultant, was elected as the fifth, sixth National Committee of the Chinese People&#39;s Political Consultative Conference Standing Committee, vice chairman of the China Democratic League (lsjt.net) 1980 was elected to the Chinese Academy of Sciences, Biology Ministry member of Academy of Sciences. formally approved by the International discovered by the Purple Mountain Observatory, Chinese Academy of Sciences, International Number 3542 asteroid named Tan Jiazhen Star in 1999 and 1985, he was elected as a foreign academician of the U.S. National Academy of Sciences and the Third World Academy of Sciences elected in 1987 to the Italian foreign academician of the National Academy of Sciences. was elected Honorary Life Fellow of the New York Academy of Sciences in 1999. <br> in 2008, Fudan University school of more than 400 man-Tan Jiazhen 100th birthday was held celebrations, <br> ; at 7:18 on November 1st 2008 in Shanghai Huadong Hospital, died at the age of 100. <br>'
);

?>