<?php

/*
	englist file:2010-10-19
	create time:2013-01-02 01:30:56
*/

return array(
'title'=>'The International Manufacturing Innovation Festival First Cailun Award &quot;',
'class'=>0,
'cont'=>'October 19, 2010, September 12 (GY), International Manufacturing Innovation Festival First Cailun Award. <br> worldwide rarely named after the name of the Chinese international awards. The International Manufacturing Innovation Festival held on October 19, 2010, the organizers will be invited to the Global Chamber of Commerce Union launched units side by side hosted, the establishment of the inventor of the \"four great inventions of papermaking Cai Lun&#39;s named \"the Cai Lun Award.\" It is reported that the annual session of the International Manufacturing Innovation Festival, will get \"Cai Lun Award\" target = \"_blank\"> Cailun Award \"countries innovative products and eminent persons to make a great contribution for innovation recognition. <br> Cai Lun (63 to 121) the word King Chung, Han, Eastern Han of Guiyang County Leiyang (Hunan Leiyang) people. The inventor of one of China&#39;s four great inventions of papermaking. <br> Cai Lun, Yongping Dynasty (75) palace eunuch. Former small yellow door, Attendants and chief still side order, Changle Taipu rank. The early Yuan Dynasty, the first year (114), Antiquorum its closure in Shaanxi Province the Yangxian ÁúÍ¤ Dipu Long Tinghou (fief), Shiyi three hundred. <br> Cailun man honest and prudent concern for the national interest, has the number of guilty Yan Yan \", Marina Bute Politics. Studious, try to act concentrate. Sinus Queen the funerary sword and other items, and also by its design, Producer, \"probably Seiko Caine secret, for posterity law\". four <br> Yongyuan (92), Cai Lun any party so yet, would of worked back often to the countryside workshop see silkworm women reeling drift floc still leaving a short-haired silk wadding bamboo bamboo mat , peeled off like silk, can be used to write, to be inspired, will collect the bark, and waste of true hemp, rags, old fishing nets and other raw materials, in the palace workshops impose filing, cook, dip, pound, copy and law, the trial plant fiber paper, finally Zaochu plant fiber paper. Yuan the Xing Dynasty (105), he will be written in the paper-making process, methods memorial together with plant fiber made out of paper, reported Han Dili, Dili big appreciated, Cailun papermaking spread quickly. This paper is called \"Caihou paper\", the country \"everyone from using Yan.\" <br> Cailun this invention, one of the four great inventions of ancient China, and made a great contribution to human civilization. Americans Mike Hart in \"Celebrity 100 list,\" affecting the course of human history, the Cai Lun came in seventh place. The opening ceremony of the 2008 Beijing Olympic Games, a special display invention of papermaking Cailun. affect the history of the world celebrities <br> China&#39;s top ten. Confucius. Qin Shi Huang 3. Genghis Khan 4. of Mao Zedong 5. Mencius 6 Emperor Wen 7 I 8. Yue Fei 9 Zu Chongzhi 10. Cailun <br>'
);

?>