<?php

/*
	englist file:1473-2-19
	create time:2013-01-02 08:47:46
*/

return array(
'title'=>'The great astronomer Copernicus&#39;s birthday',
'class'=>4,
'cont'=>'February 19, 1473 (the first month 23) Kimi great astronomer Copernicus&#39;s birthday. <br> Copernicus&#39;s Birthday \"target =\" _blank \"> Copernicus the like <br> border in Poland the Baltic coast, there is a small fishing port, the ancient castle, called furlongs Fort In the northwest corner of the castle, a watchtower this watchtower, is the world-famous astronomer Copernicus observed astronomical observatory, the history of astronomy famous Copernican tower \"since the seventeenth century, as Astronomy Holy Land has been retained to this day, every year tens of thousands of scientists come to pay their last respects, to cherish the memory of the tremendous hard work of the scientist as a human made <br> 1473 2 19, the great astronomer the earth was the founder of the theory of Copernicus was born in 1491, he went to the Polish capital of Krakow University to study astronomy and mathematics in 1496, he comply uncle Wu Kasi in Poland Torun City home of an ordinary businessman. recommendations to Italy to study canon law in Italy during his moment did not stop the study of astronomy, he conducted numerous astronomical observation and measurement to collect a large number of astronomical data in 1506, Copernicus returned to the motherland, the first to live in the his uncle Wu Kasi, the official residence of the bishop - Hull Myers, finishing his of astronomical information collected from Italy, written \"On the celestial bodies hypothesis\", which is actually \"heliocentric \"outline for 1912 uncle died, he moved to live in furlongs Fort, until the death. <br> in furlongs Fort, he bought the watchtower, the establishment of a small Observatory. regardless of the height of summer or winter He used crude homemade instruments, round-the-clock observation of astronomical spite of his persecution of the church, not afraid of spies, spy surveillance, even the outbreak of war in 1519, Poland and the Teutonic Knights castle surrounded by blood and fire case, Copernicus still a day to board turret stick to his astronomical observations he is a lifetime of effort to complete the observation of celestial bodies, written immortal masterpiece - \"celestial bodies\". This is an epoch-making book, published to begin a new era of human cosmology, Engels called the \"Declaration of Independence\" natural science from religious liberation theology <br> Copernicus Monument <br>'
);

?>