<?php

/*
	englist file:1853-5-19
	create time:2013-01-01 23:09:19
*/

return array(
'title'=>'Taiping army expedition',
'class'=>0,
'cont'=>'(Guichou April 12), May 19, 1853, the Taiping expedition. <br> 1853 19, the Taiping expedition \"target =\" _blank \"> the Taiping expedition. (history cn) In March 1853, the Taiping capital in Tianjing after to seize military site in Anhui, Jiangxi, Chun Hunan, Hubei, control Anqing, Jiujiang, shielding Tianjing, decided to launch the expedition in the Northern Expedition while June 3, the Taiping Heavenly Kingdom the life xiaguanying Vice prime minister Laihan Ying led his army two thirty thousand warships thousand vessels began by Tianjing Schomburg Jiangxi levy June 10 occupation of the north shore of the Yangtze River city of Anqing, Lai Hanying rate thousand officers and men continue westward, even grams along the river Zhu Zhen, Jin Wai Nanchang. Siege III month, her inability to withdraw Wai northward. Shixiang Zhen, WEI Jun West aid grams of Jiujiang, defeated Qing Tian town, up a victory two grams Hanyang and Hankou., Hu Akira had days raised from Anqing send troops, North accounted Jixian off, Tongcheng, Shucheng January 1854 grams of Luzhou (Hefei), Qing governor of Chiang ruin. February, Dan Xiangzhen, WEI Jun, had days to raise once again the west, defeated the Qing Viceroy Wu Wen city block ?, accounting Hanyang. and complex ·Ö±ø 3: Previously days raising economic strategy for Northern Hubei and of WEI Jun crossing the river Wai, Wuchang, Dan Xiangzhen seize Hunan. (lssjt.cn) Taiping into the Xiang Xiang Army, Zeng Guofan formation resistance. April, Dan Xiangzhen in the Jinggang defeated the Hunan Army Navy. early May, Lin Shaozhang defeat in Xiangtan, the loss of about two thousand warships, WEI Jun two grams Wuchang, June 7 - 8, the two armed forces in northern Hunan battle, because Xiao Qiang Zeng days Yang killed in Chenglingji defeated the Taiping continuous. In October, Wuhansanzhen successively fall. in December, the Qin Rigang defeat in Tianjiazhen, Hunan encroaching upon Jiujiang led his army of January, Ground in <br> 1855 West aid organizations in Jiujiang, Hukou Battle, pain F-Xiang Army Navy, follow up a victory massive counter-offensive, defeated the Qing Viceroy Yang Pei, four accounted for Hanyang, Wuchang, three grams. November, the Taiping abandoning Luzhou Wanbei situation reversed the end of the year, Xiangjun siege Wuhan Shi Dakai rate of division Western aid Hubei, Hunan Army intercept, then turn into the Jiangxi defeated Xiangjun Zhou Fengshan unit in March 1856, Ground Zhangshu town occupy more than 50 counties in Jiangxi, the siege Zeng Guofan in Nanchang, Wuhan still being the Hunan Army siege, Suizhi the stalemate war situation. The Taiping army expedition lasted nearly three years, control the Tianjing upstream Anqing, Jiujiang, the Wuchang three city, according to Jiangxi, Anhui and eastern Hubei, become Taiping Heavenly Kingdom&#39;s main strategic base, effectively shielding the Tianjing, to ensure the starving, and create the conditions persist in the struggle for the Taiping. <br>'
);

?>