<?php

/*
	englist file:1983-7-19
	create time:2013-01-01 23:36:55
*/

return array(
'title'=>'Soil and Fertilizer scientist Peibao Yi&#39;s death',
'class'=>3,
'cont'=>'July 19, 1983 (Guihai June tenth day), soil nutrients scientist Peibao Yi&#39;s death. <br> Peibao Yi&#39;s death \"target =\" _blank \"> Peibao Yi (1914-1983), also known as Pei Longxiang, soil nutrients scientist. was born on 19 March 1914 in Hubei Province, Hankou teenager read a few years, private school 1928 admitted to the the Wuchang script Hua Secondary School set up by the church. admitted to the University of Nanking College of Agriculture in 1934, the school moved to Chengdu in 1937, graduated in 1938, was agriculture degree after graduating from staying in any of the agricultural economics department teaching assistant, and has participated in Sichuan Province the invitation of Professor Huang Ruicai soil surveys and rural economic Survey 1942, transferred to the Department of Agronomy, lecturer, engaged in teaching and research work of the science of soil fertility and fertilizer, Soil Science Society of China was established in 1945, Peibao Yi is the first member of the Society one of the same year, he was the United States post-graduate studies and internship at Cornell University and the University of Wisconsin has returning in 1946, Ren Jinling University Associate Professor, Department of Agronomy, Professor. lifelong engaged Soil and Fertilizer teaching and research work for Chinese soil personnel training and the popularity of the work to make a contribution to the development of the fertilizer science, <br> 1952 he was appointed Professor of Soil Science and Agricultural Chemistry Department of Nanjing Agricultural soil survey work to participate in the Coastal Area in Northern Agricultural Chemistry Teaching and Research Group in 1954 Director in 1956, Soviet experts Asa Love agricultural chemistry workshops in China, he was involved in training graduate students to assist the Soviet experts 1956-1982, he served as the deputy director of Soil Science and Agricultural Chemistry Department in the early 1980s, China&#39;s recovery graduate education system, he was approved as the first batch of Master Instructor by the relevant departments entrusted, he and Professor Shi Ruihuo, study together to formulate a of our Crop Nutrition and Fertilization professional graduate training program for undergraduate and graduate students, he has opened a fertilizer science, agricultural chemical research, fertilization and crop nutrition and fertilization programs, and the preparation of appropriate teaching materials and handouts. these materials became about important reference materials and handouts. his painstaking Teaching, excellent results well received by teachers and students praise In 1979-1982, was elected as the 4th vice chairman of the Soil Science Society of Jiangsu Province, China Agricultural Society of Soil and Fertilizer Research Association. <br> 1983 7, 19, died in Jiangsu Province ,. <br>, Nanjing'
);

?>