<?php

/*
	englist file:1950-12-5
	create time:2013-01-02 02:26:41
*/

return array(
'title'=>'&quot;India - Sikkim peace treaty signed',
'class'=>0,
'cont'=>'December 5, 1950 (October 26), GY, India - Sikkim peace treaty was signed. <br> 1950 (lsjt.org) India - Sikkim peace treaty was signed on December 5, 2011. <br> Sikkim is a small country in the Himalayas, with an area of &#8203;&#8203;only 7298 square kilometers and a population of about 32 million people, the economy is agriculture the main industrial underdevelopment. Kingdom of Sikkim in the founding of the 17th century. <br> 1887, the British occupation of Sikkim. In 1890, Sikkim officially became a British \"protect the country\". British imperialism in South Asia after the exit, Sikkim failed to obtain independence. \"Standstill agreement\" signed in 1947 between India and Sikkim. In June 1949, the Government of India to send troops stationed in Sikkim. December 5, 1950, India and Sikkim India - Sikkim peace treaty signed 13 treaties, main content: Sikkim for the protection of the country of India, to autonomy in their internal affairs; Government of India is responsible for the defense of the territorial integrity of Sikkim India has rights in the the Sikkim territory of the garrison, the Sikkim government without the Government of India prior consent shall import any weapons and military supplies; Sikkim&#39;s external relations handled by the Government of India and regulation, Sikkim Government shall any foreign exchanges. <br> 1968, the anti-Indian demonstrations in Gangtok, for the abolition of the Treaty of printed tin. 12 king of Sikkim, Palden Dayton Du Hotspur Jiaer Sikkim Sikkim, seek to amend the 1950 Treaty of printed tin. In April 1973, the Indian army entered Gangtok, to take over all the powers of the Sikkim government. May 8 of the same year, the Indian government signed with the Sikkim \"Sikkim Agreement, the provisions of the Government of India, not only for defense and foreign Sikkim\" bear full responsibility \", and the internal affairs of Sikkim and economic\" responsible \". The agreements weaken the powers of the king, so that domestic and foreign affairs of Sikkim complete control in the hands of India. May 11, 1974 Sikkim Assembly passed a resolution, \"requirements\" India sent consultants to to Sikkim formulate the Constitution. In the same year, on September 4 and 7, the two houses of the Indian Parliament passed the amendment to the Constitution of India, the provisions Sikkim as India&#39;s \"Contact Pradesh, Sikkim, located a seat in each House. April 9, 1975, the Indian army dissolution of the the Sikkim king&#39;s palace guards, the king was put under house arrest. April 10, Sikkim Assembly passed a resolution deposed king, becomes an Indian state of Sikkim. April 14, Sikkim and held for that purpose, \"referendum\". India&#39;s parliament passed a resolution becomes an Indian state of Sikkim. was annexed before <br> <br> Sikkim Map <br> <br> Reviews: independent India inherited the British soon mantle (history pursue hegemonism. cn) <br>'
);

?>