<?php

/*
	englist file:1967-8-5
	create time:2013-01-02 00:01:01
*/

return array(
'title'=>'Tiananmen Square, millions of people criticized Liu and Deng Tao',
'class'=>0,
'cont'=>'June 29 (DingWei years), August 5, 1967, Tiananmen Square, millions of people criticized Liu and Deng Tao. review the report of the CPC Central Committee issued a <br> on the crimes of Liu Shaoqi on August 5 <br> 1967, Liu Shaoqi, Deng Xiaoping and Tao Zhu and his wife in Zhongnanhai be brutal political campaigns, and at the same time, the Tiananmen Square held a hundred million criticism Assembly. Xie Fuzhi, <br>, Qiben Yu came to the Zhongnanhai Simon \"ferret Liu FireWire, for incitement. Said: \"Liu Shaoqi, Deng Xiaoping and Tao Zhu them hiding in a cave, out are afraid to come out. They can not see the sun. You how to do in the future? Recommended that you expand the battlefield, transferred to the Tiananmen Square, opened one million of the General Assembly, to denounce Liu and Deng Tao. Rebels denounced the meeting, to deliberate on Liu Shaoqi and other personal devastation \"after the end of the struggle sessions, Liu Shaoqi was escorted back to the office, he took out the Constitution of the People&#39;s Republic of China\", (TodayinHistory.cn) protest said: \"I was President of the People&#39;s Republic of China, How do you treat me personally, it does not matter, but I defended the the Methodist President&#39;s dignity. Who dismissed my President? Will judge, but also by the People&#39;s Congress. You do this, is an insult to our country. I personally also a citizen, why not let me talk to? The constitutional guarantees of personal rights of every citizen is inviolable. Undermine the Constitution is to be subject to severe legal sanctions. \"In August, Liu Shaoqi wrote to Mao Zedong, and solemn protest for him to wear the hat of the anti-Party and anti-socialist, tendered his resignation in writing to Mao Zedong, stated:\" I have lost the freedom to Mao Zedong. \"On the same day,\" People&#39;s Daily \"published the full text of Mao Zedong years ago to write\" Bombard the Headquarters \", published an editorial:\" gun fight bourgeois headquarters. In the house of the dictatorship of the proletariat, there are two fundamental confrontation Command. One is the proletarian headquarters headed by Chairman Mao, in the bourgeois headquarters headed by China&#39;s Khrushchev. Go capitalist roaders, a handful of confrontation with the proletarian headquarters. Therefore, from the politically and ideologically, theoretically they approved deep batch through batch inverted batch smelly to the bourgeois headquarters, which is the most thorough, the most deadly destroyed. <br>'
);

?>