<?php

/*
	englist file:1900-10-5
	create time:2013-01-02 00:52:52
*/

return array(
'title'=>'The birth of the female writer Bing Xin',
'class'=>4,
'cont'=>'October 5, 1900 (, Boxer leap August 12), the female writer Bing Xin was born. Bing Xin was born <br> \"target =\" _blank \"> in the United States in 1923 Bingxin <br> Bing Xin, formerly known as Xiewan Ying, China&#39;s modern woman writer born October 5, 1900. Fuzhou, Fujian people. childhood era of living in the seaside Yantai, Fuzhou Women&#39;s Normal School in 1912, admitted to matriculation, after the mother went to Beijing in the fall of 1914, was admitted to the Beijing Pui full Girls High school Christian doctrine compulsory for her later creations have an important impact in the fall of 1918 admitted to the Beijing Union Medical College Women&#39;s University matriculation, two years after the change of Arts undergraduate after the outbreak of the May Fourth Movement, was elected student union instruments into a patriotic movement, and began to novel writing. September 1919, the first the novel two families after the advent of continuous released to society, the family, women, the problems of life as the theme problem novels, such as \"he died alone haggard\", \"Chuang Hung sister\", \"Superman\" in 1921 joined Literature Research Society in 1923, graduated from the Chinese Department of Yenching University, USA Wellesley Women&#39;s University Scholarship study in the United States in August, specializing in Western Literature May 1926, a collection of essays \"to the young reader\" published the same year by Wellesley Women&#39;s University, a master&#39;s degree after returning home, has Yenching University, Tsinghua University women&#39;s ARTS teach in June 1929 and married to a famous sociologist Wenzao by Beijing in the summer of 1936, the United States, to participate in the Harvard University established 300 anniversary of the same year the winter go to Europe and the United States access. September 1938, the family moved to Kunming. moved to Chongqing in the winter of 1940, actively engaged in cultural salvation movement. winter of 1946, to Japan with her husband. the 1949-1951 spring, in Tokyo, Japan University, he was appointed professor of literature class. autumn of 1951, returning from Japan in September 1953, he was elected to the country for the Association. significantly resent young readers, \"to the young reader\", \"Sakura Like\", \"orange lights\" also translated and published in the \"Indian Fairy Tales\" and other essays, literary works of Indian folk tales, Tagore&#39;s \"Gitanjali\", \"Tagore plays set\". either to fifth National People&#39;s General Assembly on behalf of the Fifth National member of the Standing Committee of the Political Consultative Committee, the China Federation of Literary and Art Circles director, member of the Secretariat of the National Writers Association <br> Bing Xin and little daughter <br> from left: Zhao, Bing Xin the, Xiao the dry together <br> the Bingxin <br>'
);

?>