<?php

/*
	englist file:1938-4-8
	create time:2013-01-01 22:34:36
*/

return array(
'title'=>'United Nations Secretary-General Kofi Annan&#39;s Birthday',
'class'=>4,
'cont'=>'April 8, 1938 (March eighth day) Tiger years, the birth of the United Nations Secretary-General Kofi Annan. <br> Annan&#39;s Birthday \"target =\" _blank \"> Annan and his two predecessors, Javier Perez de Cuellar, April 8, 1938, Gary <br> Annan was born in Kumasi, Ghana He studied at the the Kumasi Polytechnic University, Macalester College, Minnesota, USA, Higher Education University of Geneva and the famous Massachusetts Institute of Technology was awarded a Bachelor of Economics and Master of Management (lssdjt.cn) < ; br> Since the 1960s, Annan has worked in the United Nations Economic Commission for Africa, United Nations Headquarters, the United Nations Office at Geneva, Geneva, UNHCR, the World Health Organization department of the Middle East in 1974 after the October War, he served as the Executive of the United Nations Emergency Force in Cairo civil. early 1980s, Annan transferred back to the United Nations Headquarters, and served as the department of personnel and financial leadership in 1986, he was promoted to Assistant Secretary-General of the United Nations responsible for personnel working in the Office of Personnel 1990 Gulf After the outbreak of the war, he was the United Nations to appoint responsible with Iraq to negotiate the release of the staff of the United Nations and international organizations and Western hostages thereafter, (lssdjt.cn), the UN team led by the \"oil for food\" negotiations with Iraq in 1993 March 1, Deputy Secretary-General Kofi Annan any peacekeeping affairs, Explorer, global peacekeeping operations, has served as a Special Envoy of the Secretary-General of the United Nations responsible for the former Yugoslavia and went to NATO envoy to coordinate the relationship between the countries concerned. 13 December 1996 day, he was nominated by the UN Security Council for the candidate of the United Nations Secretary-General, 17, 2009, the General Assembly approved Annan as the seventh Secretary-General of the United Nations Kofi Annan, January 1, 1997, formally took office for a term of 5 years. <br> Annan mind calm and a sense of humor, is fluent in English, French and several African languages, is an experienced diplomat, enjoys a high reputation in the United Nations diplomats. 3 times 1997, 1998, visit to China. <br> ; Annan <br> elected in his own office <br> the beginning of his Annan immediately went to the White House to be owed by the United States contributions to the United Nations to discuss Clinton. <br> Annan in Mrs. Accompanied office UN Secretary General <br> Annan in 1997 during his visit to China with his wife boarded the Great Wall <br>'
);

?>