<?php

/*
	englist file:1885-10-12
	create time:2013-01-02 00:51:22
*/

return array(
'title'=>'Qing government of Taiwan&#39;s government province ordered Liu Ming-chuan, Taiwan Provincial Governor',
'class'=>0,
'cont'=>'The province ordered Liu Ming-chuan (, Yiyou September fifth day), October 12, 1885, the Qing government of Taiwan&#39;s government as governor of Taiwan. <br> 1885 10 12, the Qing government of Taiwan&#39;s government for the province, life Liu Ming-chuan of Taiwan governor. Sino-French War, Taiwan as a track is part of Fujian Province. After the Sino-French War, Taiwan&#39;s strategic position in the southeast coastal areas to further highlight the Qing government felt the need to strengthen the rule of Taiwan. In October 1885, the Prince Chun proposed \"Taiwan area should have high-ranking officials stationed. October 12, the Qing government edicts, the governor of Fujian to Taiwan Provincial Governor, the Fujian governor of matters by the Governor of Fujian and Zhejiang keep a close watch. (Lsjt.net) and ordered Liu Ming-chuan first governor of Taiwan. Liu Ming-chuan is to make a significant contribution to the defense of Taiwan in the Sino-French War patriotic generals. After the war, his presence in Taiwan. By the investigation personally visit the foundation, in November 1887, he and the Governor of Fujian and Zhejiang joint to the Qing court new districting scheme is approved. The program is: in Taichung, Changhua, the establishment of the provincial capital; additional Taitung Zhili; of Keelung, Penghu, Puli community Haiphong powerhouse, set for Hall to re-powers. Officials set with the mainland. The original set of local institutions, more than the CD, ranging from increasing, not set by set. Administrative Region by the eight counties of the three halls of the Second House expanded state (Taitung Zhili). Three House (Tainan, Taiwan, Taipei), four Hall (Puli community, Penghu, Keelung, Hualien Harbor), 11 counties (Taiwan, Changhua, Yunlin, Miaoli, Anping, Fengshan, Chiayi, Hengchun, freshwater, Hsinchu , Ilan). In this way, the entire island of Taiwan, into real life. Liu Ming-chuan governor of Taiwan \"target =\" _blank \"> Liu Ming-chuan postwar governance station there are five years, in the province of fortification, got rid of officialdom, Gaoshan unity, build railways run of Posts and Telecommunications, Qing Fu financial initiatives innovative learning material contribution, the change the backwardness of Taiwan, and to accelerate the development and construction of Taiwan, from the important historical role. <br>'
);

?>