<?php

/*
	englist file:1940-9-23
	create time:2013-01-02 00:31:08
*/

return array(
'title'=>'Things storm-election Hu Shi as president of Academia Sinica from',
'class'=>0,
'cont'=>'September 23, 1940 August 22 (Dragon), the by-election Hu Shi as president of Academia Sinica things storm big play. <br> 1940, Chiang Kai-shek made Zhu Jiahua any president of Academia Sinica, the Hu Shi post of ambassador to the United States unchanged the decision after around the by-election caused by Hu Shi as president of Academia Sinica regarding storm was averted. 5 <br> 3, Cai Yuanpei died in Hong Kong, president of Academia Sinica vacancy need-election. At the program, the should Academia Sinica council will choose candidates, selection appointed by the National Government. <br> attention for academic leaders Hu Shi, Weng Wenhao Zhu Jiahua trio, especially Hu Shi loudest voices. Hu Shi being ambassador to the United States any (history. Cn) Kung are not satisfied the appropriate Ambassador Hu, Yan Huiqing replace him right now to take this pretext tune he returned home, and then the ambassador to the United States to appoint Yan Huiqing successor. Although this is secret, but scholars also a rumor. This time, Chiang Kai-shek and pro under the sliver to \"lift out\" Gu Meng Yu, violated the academic. Eve of the election, the Councilors feast together, Yinke speak about the meaning of academic freedom, advocated \"Dean prestigious foreign scholars must\" privately that \"We can not single a few Mr. Chiang&#39;s secretary. They immediately do a \"false voting, Weng Wenhao 23 votes, Hu Shi was 21 votes, Zhu Jiahua 19 votes. Hu Shi votes less for friends deliberately not vote for him, for fear that he was selected and removed from the Ambassador to the United States any. <br> things known to Chiang Kai-shek, his big upset, HH Kung said: \"Now they want to appropriate the, it telegraphed to get him back! \"Kung, Yan Huiqing very excited, and four to disseminate the message said\" Hu Shih is necessary to return any of the Academia Sinica long! \"Ms. Hu wrote to Hu Shi, want his declaration quit. Hu Shi&#39;s reply to his wife said: \"I do not want to do the dean, but I Statement quit it if I could not bear to lose now official. \"The last council official election results: Weng Wenhao Zhu Jiahua each had 24 votes, Hu Shi was 20 votes [l $ j¦Ó.c¨½ Siguang 6 votes, Wang Shijie 4 votes, Gu Meng I had a ticket. Because this election stirred into the many contradictions, Chiang Kai-shek and other late September before making a final decision: Zhu Jiahua more politically Chiang Kai-shek and his trusted, then let him as Acting President of Academia Sinica. Ambassador Hu Shi positions unchanged. (History. Com) <br> Chiang Kai-shek To Wang Shijie power to Hu told him that \"rumor tune brother to return, are caused by Academia Sinica problem. Government feel the United States duty more important than the Academia Sinica, until atonal brother repatriation decision. At this point, the dust settles. <br>'
);

?>