<?php

/*
	englist file:1793-1-21
	create time:2013-01-01 18:46:14
*/

return array(
'title'=>'King Louis XVI was guillotined',
'class'=>0,
'cont'=>'(, Yam Tze years the twelfth lunar month, the tenth day of this seventh month), January 21, 1793, King Louis XVI was guillotined. In the <br> 1793, King Louis XVI was involved in the design of the guillotine killed 1 <br> 1793 21, the sky was raining, but around the Revolution Square in Paris, but packed with all kinds of people, and these people are very excited. Their side enthusiastically remarked, while eagerly overlooking the distant road. Soon, a band of soldiers escorted a carriage came slowly. To the square, four soldiers from the car to charge the next person to remand him to the guillotine, then broke out in a fit of rage voices masses: \"hang him! \"Cut off his head! To \"<br> him is the history of France&#39;s famous tyrant Louis XVI! The sound of the anger of the masses, \"splash\" kneel before the priest, the priest in one hand and in the chest paddled cross in one hand and stroked his head, and said slowly: \"son of Shengdeluyi, ascended to heaven. ! \"After three executioners put him in the guillotine, starting guillotine the decapitation knife suddenly fall, ...... deafening cheers broke out among the masses. the <br> of King Louis XVI Following in 1774, when France year after year famine, hungry people everywhere, factory closures and unemployment, but only know that Louis XVI pleasure, ignoring the affairs of state, big spenders king Houma Li Anthony French debt, financial crisis led to a political crisis in 1787, finally broke out in the late 18th century French bourgeois revolution. May 1789, three of the 175-year-old was forced to convene interrupt. Paris, July 13, the outbreak of the armed uprising of the people (l $ j¦Ó.c¨½)] 14 capture of the Bastille. 19 Louis XVI was forced to court by the Versailles move back to Paris. June 20, 1791 make-up to be detained. September ratification of the 1791 Constitution, something goes wrong again. In April 1792, he colluded with foreign enemies and fleeing aristocracy, in an attempt to crush the revolution. August 10, was arrested after the revolution. On September 22, the National Association announced the abolition of the monarchy and the establishment of the first French Republic. January 15 of the following year, the National Association of formal judgment of Louis XVI to death. In the cheers of the masses, the domineering tyrant finally decapitated. King Louis XVI, <br> <br> King Louis XVI brought to the guillotine <br>'
);

?>