<?php

/*
	englist file:1998-4-21
	create time:2013-01-01 21:21:43
*/

return array(
'title'=>'Chinese government outlawed pyramid schemes',
'class'=>0,
'cont'=>'April 21, 1998 (March 25) Tiger years, the Chinese government banned pyramid schemes. the the <br> Distributor MLM banned wait for return <br> 1998 April 21, 2010, China announced that it no longer allow any form of MLM business activities, has approved the registration of the latest 10 before January 31, apply for modification or cancellation procedures. At this point, from the 1990 Sino-US joint venture Avon MLM Co., Ltd. will be the introduction began, the MLM way to go in China for nine years after coming to an end. <br> as a marketing, MLM origin in the United States in the 1940s, popular in Japan, Taiwan and other places. Last year, more than 130 countries and territories worldwide MLM, employing 26 million, with sales of over 75 billion U.S. dollars. <br> due to reduced circulation, simple and convenient, guaranteed the back section, and a lower risk of job opportunities for low-and middle-income classes, MLM is a more mature approach to marketing in the developed market economy countries. <br> essence, MLM marketing model is a demand-oriented. MLM is a more common way of selling abroad. It is not a sleight of hand tricks trick, it is definitely not a scam of water to oil, therefore no more than another way of selling the opportunity to make a fortune. However, the MLM to China, he was rendering to the 20th century, the last chance to riches. Ignore the sales of the product quality and the actual market demand, keen on hunting capitation and development off the assembly line, so MLM become \"rats\" mysterious chain synonym. Distributors&#39; business philosophy is this: \"I lie to you, because I love you;\" wealth is not a friend, a friend they can be turned into wealth. <br> 1998 mania MLM industry was banned. Thousands MLM visitors flocked to the front of the Wuhan Hankou District, Wuhan&#39;s largest distributors of San Tin, this honor has been two days and nights waiting in the rain holding performance single mother and her daughter. <br> the personal feelings Habitat society under some distributors cult-like Zhonghuo and the advocacy of human became a fortune advantage. A small town on the women to sell their own just gave birth to a baby, get 9000 dollars joining the scheme, groups of laid-off workers around the house, only the savings they buy a few thousand dollars ( fact worth only four or five hundred] MLM products; Some farmers sell cattle, do no farm work, carrying baskets of eggs and quilts to the far field to participate in entrepreneurship seminars. \"<br> however, Chinese people get rich by doing MLM it? addition to the the some heart Blackhand spicy unscrupulous distributors through °ì°à earn capitation fees the sordid means of plunder profiteering outside became the stepping stone to their wealth, the vast majority of distributors. suffered a major loss in MLM MLM disabled so people and more harassment get bored consumers Sarkozy said: should. <br>,'
);

?>