<?php

/*
	englist file:1558-9-21
	create time:2013-01-02 01:41:50
*/

return array(
'title'=>'Holy Roman Emperor and King of Spain, Charles V died Iust monastery',
'class'=>0,
'cont'=>'(Wu Wu, August tenth day), September 21, 1558, the Holy Roman Emperor and King of Spain, Charles V died of Iust monastery. September <br> 1558, Holy Roman Emperor and King of Spain, Charles V died of Iust monastery. <br> Charles V (Holy Roman Empire) (Lssdjt.com) the title of the King of Spain: Carlos I; Holy Roman Emperor title: Carl V; (history www.TodayOnHistory.com ) known as Charles of Austria (1500 -1558 years 21 days) before the throne, the King of Spain (reigned 1516 -1556), Holy Roman Emperor (1519 -1556 years bit), king of Sicily (known as Carlo I, 1516 -1556), King of Naples (known as Carlo IV, 1516 -1556), the supreme monarch of the Low Countries. Europeans&#39; minds, he is the \"Hapsburg the hegemony era\" of the protagonist. <br> from the age of 15, he was elected the \"Germanic Holy Roman Empire\" Emperor, to show he is an ambitious person. In order to win the right to rule on the Italian peninsula, from 1521 to 1544, he launched a continuous 4 times on the meaning of war. He then war and Oriental Turkey Suleiman, an attempt to seize North Africa; addition, he continuously engaged in the conquest of the American continent. He is full of military forces with the the bloody looting and killing, four Italian war it suffered a devastating catastrophe, as long as 150 years to make meaning in a dark period. The conquest of Central and South America is inhuman, where he was forced to the implementation of a brutal, brutal feudal rule. Central and South American Indians indigenous to the mid-16th century, had been killed up to 1,500 people. In addition, he with the Pope, for the maintenance of the feudal rule of the Catholic Church, the cross and the stake as a magic weapon to safeguard Empire, the most cruel persecution of the people in China. German peasant uprising occurred in 1524, 10 million farmers have been killed. Him around the establishment of the Inquisition, to destroy religious reform movement, killing infidels, the stake in the Empire heresy court always burning. Thousands of people were burned to death. After the outbreak of the war in 1552, Charles V was the series defeat in the Augsburg religious peace treaty in 1555, then signed with the princes. <br> 1555 after the failure of a last-ditch effort to defeat Protestant forces, Charles V began from the political life. His own personal empire - Spain and the Low Countries passed to his son Philip II; Holy Roman Empire to his brother Ferdinand I (October 25, 1555 to give up the the Netherlands throne to Philip ; January 16, 1556 to give up the throne of Spain to Philip; [而身d芋y身里h貝 $ 而身ry.c身m] 1556 to give up the the emperor throne to Ferdinand). <br> Charles V&#39;s twilight years spent in Extremadura, Spain Iust monastery. Charles V died on September 21, 1558, after 20 years of his life, he has been subject to torture of gout. <br> <br> <br> watch his behavior while a tyrant <br>'
);

?>