<?php

/*
	englist file:1997-12-3
	create time:2013-01-02 02:19:04
*/

return array(
'title'=>'The ancient city of Pingyao inscribed on the World Heritage List',
'class'=>0,
'cont'=>'December 3, 1997 (Dingchou the winter in early), the ancient city of Pingyao inscribed on the World Heritage List. The twenty-first session of the UNESCO World Heritage Committee <br> passed a resolution on December 3, 1997, the ancient city of Pingyao in Shanxi Province, inscribed on the World Heritage List. The World Heritage Committee, the expert investigation and evaluation that Pingyao in China the best preserved an ancient county, is an outstanding example of Chinese Han Nationality cities in the Ming and Qing Dynasties, the development of Chinese history, demonstrate a unusually complete picture of the cultural, social, economic and religious development. \"<br> Ancient city of Pingyao in central Shanxi the Jinzhong region, 90 kilometers away from Taiyuan, founded in during the Western Zhou Xuan Wang, since 2800. Since China adopted the system of prefectures and counties in 221 BC, Pingyao has been the county seat. The ancient city of Pingyao original rammed earth wall, a smaller scale. Hongwu years, began to expand into the scale now, 600 years, the urban area and planning pattern remained essentially unchanged. Integrity of the preservation of the ancient city walls, the city Confucian Temple Dacheng Hall, Qingxudong concept, Cai Shenmiao, Municipal Building, County Yamen, Kichijoji ancient buildings arranged in order, there are 3997 houses, of which more than 400 high preservation value. City by four streets, eight side street, consisting of seventy Lane street pattern, fully embodies the ancient ritual system level. Basically saved along the main street, commercial shops built in the 17th to 19th centuries. The whole city completely embodies the the 18-19 century historical appearance. the <br> Pingyao ancient city, including the ancient buildings and monuments, quantity and grade are rare, including built in the North Han day will be seven years, as China&#39;s third most valuable old trees framed building town of Temple; Rebuilding in Dading three years, the National existing small Confucian Temple Dacheng Hall, as well as the world-famous Temple, Shanxi and so on. Pingyao is also one of the well-known China&#39;s Shanxi Merchants \"birthplace. Daoguang four years, a new way to borrow --- ticket number exchange was born in the Pingyao city Rishengchang number of epoch-making significance in the history of China&#39;s financial. <br>'
);

?>