<?php

/*
	englist file:1968-4-3
	create time:2013-01-01 22:23:24
*/

return array(
'title'=>'Table tennis three heroes were persecuted to death',
'class'=>3,
'cont'=>'April 3, 1968 (, Shigenobu In March sixth), table tennis three heroes were persecuted to death. April, <br> 1968 Chinese table tennis three heroes Fuqi Fang, Jiang Yongning, Rong Guotuan cleaning class ranks movement, was tortured to death. The Fuqi Fang, <br> back from Hong Kong in 1952 to participate in the National Table Tennis, men&#39;s singles runner-up. He is one of the the 24th Table Tennis Championships men&#39;s team three main players in the Chinese team, since 1958, the men&#39;s coach of the national table tennis team in 1965 to join the party. He was the vice chairman of the Chinese Table Tennis Association, the fourth member of the National Committee of the Chinese People&#39;s Political Consultative Conference. Clean-up class ranks, the Fu Qifang was Jiudou beaten. In the early morning of April 16, he hanged himself. Jiang Yongning, <br> back from Hong Kong in 1952 to participate in the National Table Tennis, won the men&#39;s singles title. Is one of the main players of the 24th World Table Tennis Championships men&#39;s team. 1956 was the title of a top athlete. In 1957, he was appointed the coach of the national table tennis team, he served as head coach of Beijing table tennis team. He usually like to watch the newspapers, the \"Cultural Revolution\" was said to be in order to collect intelligence, May 10 is isolated review copy of his house and found a Jiang Yongning boyhood photos, photo Jiang Yongning clothes of small facial sun flag, he decided that he is \"Japanese spies\" May 15, to make him confess, and beaten him. On May 16, he was in the the Xiannongtan quarters 4 hug by hanging. <br> capacity Guotuan, back to the mainland from Hong Kong in 1957. 1959 was the 25th world the Ranger Ball Championship men&#39;s singles champion, world champion sports. The table tennis women&#39;s team coach in 1963 he was appointed, to contribute to the Chinese women&#39;s team for the first time to win the women&#39;s team title. \"Cultural Revolution\", he represents the table tennis team definite shape a Qingzhan report to the central result, the report is not only returned, but also forced to check the \"mastermind tone\". Rong Guotuan under tremendous pressure. 4 o&#39;clock in the morning on June 20, he hanged himself on a tree. Suicide note in the pocket he wrote: \"I am not a spy, I do not doubt. I let you down. I love my honor than his own life. <br>'
);

?>