<?php

/*
	englist file:1865-4-3
	create time:2013-01-01 22:33:07
*/

return array(
'title'=>'In the American Civil War, the Union forces occupied the Confederate capital of Richmond',
'class'=>0,
'cont'=>'In (Yi Chou, March eighth day), April 3, 1865, in the American Civil War, the Union forces occupied the Confederate capital of Richmond. <br> 18 century after the American War of Independence, the establishment of a federal system, the ruling coalition by the bourgeoisie and the plantation slave owners. <br> 1860, called for the maintenance of the federal unified, is known to oppose the expansion of slavery, Lincoln was elected the 16th President of the United States, Southern slaveholders felt to lose its power, began to create a split, deliberate rebellion in early 1861, The Southern establishment of the southern states alliance. Fort Sumter, April 12, the southern rebels shelled federal army openly provoke civil war. April 15, Lincoln was forced to announce the southern rebel states, the recruitment of 75,000 Volunteers fight to restore federal unity. (Lssdjt.cn) <br> 1861, 7, 40 km from Washington the horse that Texas City occurred the first battle, the Confederate army defeated the federal army was fewer, Washington almost fall. Since then, the masses held demonstrations requirements of the emancipation of slaves, and give farmers the land, save a critical situation. <br> In order to change this situation, the Lincoln administration to take timely two major reform measures. May 20, 1862, the government enacted the Homestead Act, \"September 22, they issued the Emancipation Proclamation. After this war situation occurred a fundamental change in the federal army gradually mastered the battlefield initiative. <br> 1863 summer, the federal army to counterattack, following after the decisive victory of the Battle of Gettysburg, July 1 -3, captured the Mississippi River downstream of Vicksburg on July 4, offensive forces to destroy the allies, completely reversing the situation of the war. Then, the Federal Army adopted a new strategy to actively offensive, and by the end of 1864, the South is almost paralyzed state. In In November, <br> 1864 Lincoln was re-elected by an absolute majority of the president, the South has the last word. <br> 1865, the federal military capture of Richmond. April 9, General Robert E. Lee, the commander-in-chief of the allied forces led the troops to 2.8 million people to surrender to the EFF, the American Civil War to the victory of the North and came to an end, the American Recovery unified. <br>'
);

?>