<?php

/*
	englist file:1876-7-3
	create time:2013-01-02 00:16:44
*/

return array(
'title'=>'China&#39;s first railway Songhu Railway opened to traffic operations',
'class'=>0,
'cont'=>'(Rat-year leap 12 May), July 3, 1876, China&#39;s first railway Songhu Railway opened to traffic operations. <br> <br> Songhu railway is the first railway in China. From Shanghai through the Jiangwan to Wusong, approximately 14.5 kilometers. In 1866, in China, the British Minister to request building railroads, to the shipping to Wusong the goods shipped by rail to Shanghai, without the clear approval of the Government. Jardine Matheson, British business organization \"Wusong Road Company in 1875, the railway equipment shipped from the UK to privately roads. Xiu Shanghai to jiangwan section in June 1876, opened to traffic in early July, 762 mm gauge rail weighing 13 kilograms per meter, a \"pilot\" locomotive traction passenger and freight vehicles. During the construction period, along the people against the outsiders to build railroads in China, and destroyed the \"Company\" Jiangwan offices. August 1876 train crushed pedestrians, who were furious, \"Company\" forced the suspension of service on the train. In October 1876, the Qing government signed with the British Minister bribed the terms of the Wusong Railway, but the \"Company\" continues to roads, the opening of Shanghai to the full range of Wusong completion on December 1, 1876. In September 1877, the Qing government to redeem this railway will soon demolished the whole road. February 1897 rebuilt the Songhu railway, changed to standard gauge, weighing 32 kilograms per meter rail. Completed in August 1898. Merged into the Shanghai-Nanjing line in October 1904, was renamed Songhu Extension. Japanese occupation of Shanghai in 1938, put line Hejiawan to the gun Taiwan trestle line removed. After the victory of the War of Resistance Against Japan, the the Songhu railway come Chichiawan to repair to Yun algae Bang, a total length of 13.68 km per day when it drove off the passenger train. The 1958 the the Shanghai hub station built by the construction of feeder Hejiawan then Nanxiang Station as a the Shanghai hub within the dedicated freight line to line paragraph Tian Tong Hejiawan,. In In the 50s of the 20th century railway reduced to? algae Bang South Bank, a total length of 14.53 km. The liberated Songhu line both passenger and freight transport line, annual passenger million people. 1,944,000 passengers in 1959. 1963 due to the development of the city bus transport, railway-Tian Tong crossing seriously affect bus operations. January 1963 across the board to stop the Spring Festival passenger, stopped in 1988 after the freight. April 17th, 1997 the Shanghai North --- jiangwan station was dismantled. <br> Commentary: China&#39;s Railway finally scratch developed. \"Train sound, tons of gold,\" To the rich, multi railway ah. <br>'
);

?>