<?php

/*
	englist file:1907-8-3
	create time:2013-01-01 23:48:37
*/

return array(
'title'=>'People&#39;s Liberation Army generals Fu Qiutao birth',
'class'=>4,
'cont'=>'August 3, 1907, June 25) (DingWei years, the People&#39;s Liberation Army generals Fu Qiutao born. Anding Town of <br> Fu Qiutao born \"target =\" _blank \"> Fu Qiutao (1907-1981), Hunan Province Pingjiang Naruto Hermit. had names Xugao, Takena August 3, 1907. childhood to the landlord put cattle, to do long-term employment in 1925 to participate in the workers&#39; pickets Pingjiang peasant uprisings in 1927 and joined the Chinese Communist Party in 1929 transferred to the Chinese Workers&#39; and Peasants&#39; Red Army in 1933, is one of the main leaders of the revolutionary base in Hunan, Hubei, Jiangxi Agrarian Revolutionary War Ren Pingjiang County farm laborers trade union chairman, secretary and secretary of trade union chairman of the CPC Hunan, Hubei, Jiangxi Province, Hunan, Hubei, Jiangxi Military District Director of the Political Department of the CPC Hunan, Hubei, Jiangxi Province, secretary of Hunan, Hubei, Jiangxi Military Region political commissar. participated in the South for three years guerrilla war. Sino-Japanese War, he served as the New Fourth Army, the first detachment of a regiment, a detachment deputy commander, commander and political commissar, the New Fourth Army Seventh Shifushichang. Wannan Incident, he made a resolute struggle against the rightist route led his troops with the enemy fought a bloody war, in the case of exhaustion, organizational forces dispersed tight encirclement, save the backbone of the New Fourth Army during the War of Liberation, Ren Lunan members of the military and political, party secretary of CPC Lunan District, LUZHONGNAN Military Region Commander supporting the front of the chairman of the Committee of East China, supporting the front Command commander, the CPC Central Committee and first deputy secretary of the Shandong Branch of Shandong Military Region deputy political commissar. TodayinHistory.cn] After the founding of the People&#39;s Republic of China, Shandong Military Region deputy commander , Central the demobilization Committee Secretary-General and the Central Military Commission, People&#39;s Armed Minister, (1 $ dj¦Ó.c¨­m) Minister of People&#39;s Liberation Army General Staff queue mobilization Minister, deputy director of the Central Military Commission, People&#39;s Armed Committee, the General Staff consultant. 1955 was awarded the rank of the second, the third member of the National Defense Commission, the second and third National People&#39;s Congress, the fourth, the fifth member of the Standing Committee of the National People&#39;s Congress, the Communist Party of China the seventh and eighth National the General Assembly representatives at the Third Plenary Session of the Communist Party of China was selected as the Standing Committee of the Central Commission for Discipline Inspection. passed away in Beijing on August 25, 1981. (L $ dj¦Ó.§«§§T) <br>'
);

?>