<?php

/*
	englist file:1900-9-3
	create time:2013-01-02 01:29:52
*/

return array(
'title'=>'The Boxer Rebellion four cutting Jiaobu the kill the outskirts of Beijing Boxer',
'class'=>0,
'cont'=>'August tenth day (Boxer), September 3, 1900, the Eight-Power Allied Forces four cutting Jiaobu kill Boxers in the suburbs of Beijing. Boxers in <br> Caishikou killed <br> September 1900, the Eight-Power Allied Forces in the capital continue to search kill Boxers and soldiers constantly to Kinki around the hair destroy group. The public see \"the Russian soldier brigade from Chongwenmen North, in the Kinki destroy Boxer, triumph and spin, was CYL many, relying on the immediately. U.S. soldiers are also a team. \"<br> 5 foreigners door to door, to catch people in the streets, it is called coolies went outside with four townships cut fight sorghum, corn, grass, sent to each unmanning at lift throughout the horses . Foreigners between Jieyou charge with a little do not work hard, that is, being beaten and suffering can not be made, regardless of the Blackstone the NGS conjunction arrest, multi-family caught \". <br> 7 days, the Eight-Power Allied Forces to H Xihongmen group China. \"Another boxing Huangcun also a lot of foreign soldiers to hit scattered, then the momentum H of the village, the level of Hart and Yi Kuang words: \"Recently, the Nanyuan when gunfire attack foreign troops more than a decade Chi Wang, actually shot. Boxer hundreds\". on <br> 11, the coalition of more than 1,700 people, carrying cannon six and tapping Liangxiang county. The Boxers killed more than 250 people, breaking the city. Group people killed countless. The coalition forces Veuve Beijing. The eyewitness said: \"The foreign troops brigade by Chang-door drumming into by more than a thousand. Team leader, to execute the Liangxiang a the Tuen Boxer flag, another Dao flag, complex dozen flags, the MILLIONS books &#39;Boxer&#39;, another &#39;neighborhood watch&#39; words; the Boxers Daomao pieces. The step team first, the Colts in paoche folder line. The trailer is tethered cattle Three donkeys a. \"Liangxiang group people\" count dead four thousand people. (L $ j¦Ó.c¨½) \"<br> the same day, the the Imperial household Ministry Yashu burned extended to the Ministry of Rites. \"The Ministry of treasury money were countries banditry an empty, it is set on fire to never an excuse.\" on <br> 16, the Eight-Power Allied Forces composed Badachu along the crusade team \"to the extermination Boxer, blow up the pagoda a burned Linh Quang, pen and ink Park, etc. temple. (Lsjt.org) <br> 19, the coalition forces to the outskirts of Beijing Xishan Guanyin Village extermination Boxer, the village fire destroyed, the group China over a hundred people were killed. <br> the Eight-Power Allied Forces in the suburbs of Beijing will be caught Boxers slash at smb. place <br> the Japanese in the Qing government policeman assistance Andingmenwai beheaded captured Boxers . <br>'
);

?>