<?php

/*
	englist file:1966-12-16
	create time:2013-01-02 02:04:44
*/

return array(
'title'=>'Death of Peking Opera artist Ma Lianliang',
'class'=>3,
'cont'=>'The (Heigo the winter in early Friday), December 16, 1966, death of Peking Opera artist Ma Lianliang. the <br> Ma Lianliang death of target = \"_blank\"> Ma Lianliang in the the Peking Opera Huaihe Camp in ornaments the the Kuai Toru <br> 1966, (history. cn) the opera artist Ma Lianliang because of \"Hai Rui Dismissed from Office\" the drama suffered persecution, died on December 16 of the year. <br> Ma Lianliang (1901-1966) Chinese opera artist. work Laosheng. Hui. Beijingers. 9-year-old into the Beijing hi together into Coban Arts and by the industry in Ye Chunshan the Cairong Gui, Xiao Changhua, GUO Chun Shan, Ru-Lai Qingdeng, the first martial arts students, and later changed to the older students 10 years of age or older students, the highlight of the stage after course completion, he continued learning, home to the Sun Juxian, Jiahong Lin, Jing Ran absorption I (tert-rock ) sent a long, long-term artistic practice developed into a unique horse representational art. served as the head of the Beijing Opera Troupe of Beijing, Beijing opera College Principal and other staff. went to North Korea show sympathy for the Chinese People&#39;s Volunteers, led a delegation to Hong Kong to perform promote national culture. Cultural Revolution began, due to the \"Hai Rui Dismissed from Office,\" a drama by the cruel blow, was tortured to death. Ma Lianliang art seriously, deliberately refinement, not only to sing, read, do the all-round development, and martial arts bedrock deep. voice cool and bright, singing euphemism, in the Hearty see pretty, delicate in to see free and easy, many aria has popular swept the country, especially in his later years, to participate in the the newly historical drama and modern opera performances, singing, read white, working there to create and development has reached the consummate state that he attached great importance to the integrity of the theatrical arts, mutual co-operation between the roles, demanding, meticulous band attention to yueqin accompaniment effect because of his advocacy, his clothing, makeup, helmet head the, Rankou have innovative creation, before the band additional screens, bands and performances separate, purify and beautify the stage. \"Majestic\" on behalf of repertoire, \"by the wind\", \"Kanroji\", \"Four Scholars \",\" Su Wu sheep \", the\" Spring and Autumn pen, \"a handful of snow\", \"phase\", \"Hai Rui Dismissed from Office,\" \"Orphan\" traditional opera and new historical operas \"Azalea Mountain\", \"years years more than a modern opera. disciples have Wang and Lin, Wang Jinlu words less friends, Limu Liang, Ma Changli, late Jin Sheng, etc.. he starred in the \"Majestic\" and \"pressure the United States case\" has been filmed as an art film, there is \"Ma Lianliang performances screenplay anthology Yukiyo. <br>'
);

?>