<?php

/*
	englist file:1931-8-16
	create time:2013-01-02 01:06:33
*/

return array(
'title'=>'The Lanzhou occurred REIMAA Incident',
'class'=>0,
'cont'=>'(, Xinwei July third), August 16, 1931, Lanzhou Extremadura Incident occurs. <br> in August 1931, Lanzhou Extremadura Incident occurs. Early 1931, Ma Hongbin any Gansu provincial governor, the local forces of the far side, Gansu decree clinics, however Lanzhou nearby counties. Newly eighth division of the Lei Zhongtian cowardice and incompetence of Ma Hongbin want to replace it. When any of the members of the Gansu provincial government Marvin car, the Gansu provincial government reorganization in July, has not been greatly disappointed by the provincial governor, or the Home Minister posts To Lei Zhongtian strength to change Gansu councils achieved their status . August 16, Lei Zhongtian Ma Hongbin seizure, with himself as the commander-in-chief of the Gansu Provincial Security, the Chairman of the Gansu provincial government agent by Marvin car. the Incident <br> Ma Hongbin, son of Ma Liqing went to Xining, Ma Lin to the rescue. Ma Lin then with entourage line to the 70 miles from Lanzhou Kansui Fort, the send Qinghai Province Education Department Director Yang Xiyao held the letter met Lei Zhongtian. Ray asked Ma Lin to Lanzhou to discuss face-to-face everything. The Ma Lin letter, proposed, personally went to the blue into the city with 600 cavalry, was the refusal of the mine. The Ma Lin mediation invalid, Suiqu Road, River State, Xunhua area, reversal of Xining. The after by Wu Pei-fu to Lanzhou from to intercede before Ma Hongbin release. <br> 8, 30, and Chiang Kai-shek for this call Lei Zhongtian: \"days then reported that the horse Chairman banned rebel center of lawlessness, if true, it is. Limit text to the the upcoming horse Chairman restoration of liberty, line facilities the terms of reference. Central command, never change. Hereby instructed brother investigating the case, and the investigation and handling of the situation, fire urgent telegram complex. \"<br> Office since Ma Hongbin was detained, lasted only 8 months, but attracted Wu Pei-fu into self-Chuan Gan. Unite Wu into Gan, has given rise to the Shaanxi army into Gan, mutual fights, turf battles, and exacerbated by the Gansu chaos. <br> Rating: Extremadura Incident Gansu Republican history and even an important event in the history of the Republic of northwest Gansu fall into the turning point of the Chiang Kai-shek ruled by Feng Yuxiang National Army forces. Wu Pei-fu performances in the incident and the final scene in the Republic of the political arena. Therefore, the study of the political history of the Republic to study the biography of Wu Pei-fu, can not but here some discourse. <br>'
);

?>