<?php

/*
	englist file:1941-8-31
	create time:2013-01-02 00:38:57
*/

return array(
'title'=>'The Border to complete the democratic elections',
'class'=>0,
'cont'=>'(Government House in July, the ninth day), August 31, 1941, the completion of the Border democratic elections. Eighth Route Army troops to take part in the elections Border Region Senator <br> 1941 June 15, 2010, the General Assembly, according to the CPC Central Committee on the implementation of the new democratic constitutionalism and the establishment of the \"three-thirds\" behind enemy lines, anti-Japanese democratic regime The instructions in the border area for the first time in North China behind enemy lines to carry out democratic election campaign. The election campaign in four phases: June 15 to July 10 for the preparation phase; District representative will be completed by July 10 to 25 and the mayor elected; 25 July to 15 August County Parliament and the magistrate elected, and at the same time to complete the election of the National Assembly; August 15 to the end of August to complete the border area councils the Border Region Executive Committee, various occupational groups items as delegate to the National Election. <br> in the preparation stage, the Border Administration Committee has released the mobilization and organization of the elections at all levels, at all levels of the election preparation meeting decided, the Interim Regulations on the Organization of the \"Border side counties, district and village \",\" border area council Provisional Regulations \",\" Border Provisional Election Ordinance \"instructions and regulations, launched the Village Theatre Company, the publicity team, Choir deep rural areas, the guerrilla zones, to meet the enemy zone propaganda performances, each arranged County issued propaganda and mobilization election tabloids more than 100 species, more than 10 million copies, mobilization since the boom of the political participation of the masses of the Border Region. The parties of the border area, at all levels, civic groups actively choose candidates, announced unexpectedly election program, and to participate in the election campaign. <br> in the democratic election, the border area around the election people accounted for an average of more than 80% of the total number of voters, the central area is more than 90%, the guerrilla zones more than 70% women candidates of 83.6%. This phenomenon is unprecedented in the history of China. Border Region People&#39;s Democratic election district on behalf of the Council and the Mayor, county council and county magistrate Border Region Senator, Executive Committee and representatives at the National National Assembly election lasted more than three months, the initial establishment of the county, district, public opinion and administrative organs of the the village three anti-Japanese united front, completely destroyed in the border area within the institutions of the old regime, so that the border region to achieve the fundamental transformation of the regime and the new democratic political. <br>'
);

?>