<?php

/*
	englist file:1759-11-10
	create time:2013-01-02 02:32:37
*/

return array(
'title'=>'German playwright Schiller&#39;s birthday',
'class'=>4,
'cont'=>'November 10, 1759 (September 21) JiMao German playwright Schiller&#39;s birthday. dramatist Schiller&#39;s birthday of <br> Germany \"target =\" _blank \"> the Schiller <br>\" robber \"Germany in the late 18th century a great impact screenplay times in early 1782, when the Sea wood staged immediately aroused strong social reaction. screenplay hero Carl Moore is a pure young love reading Rousseau article forced decadent social environment, join robber team Shafujipin feudal society of the time, the unreasonable legal and the hypocritical religious criticized he publicly announced their lofty ideals; \"Germany will become a republic, Rome and Sparta, compared with, but nunnery.\" At the time, Germany is not a unified country , but split into 300 of feudal small-state. bossy brutal rulers of these small states to crush the people, \"robber\" This play is a staged, like dry wood on a fire ignited the passion of the people against tyranny, the whole society by storm. Schiller, author of the <br> \"bandits\", the distinguished German poet and dramatist (on TodayOnHistory.com) 1759 11 10 born in Wuerttemberg Duchy of Marbach City, his father was a surgeon, and later Ren Xiaojun officer in the army of the card ¡¤ sides will root Duke and his mother was a baker&#39;s daughter. 1768, Schiller enter the Latin school, preparing for the future in accordance with their own hobbies and the wishes of the parents, into the seminary However, when Schiller graduated in 1773, the two sides will root Duke forced him into the military academy Military Academy Duke culture servant agencies heavy no freedom here, Schiller was being detained for eight years during this period , he contacted the works of Shakespeare, Rousseau, (L $ dj¦Ó.§«§§T) Goethe&#39;s and proceed secret written screenplay \"bandits\". graduated from the Military Academy, he went to the capital of the Duchy of Stuttgart any Military, continue authoring \"bandits\". 1781 publication of \"bandits\", staged in 1782, Schiller this purpose by the two sides will root Duke solitary confinement two weeks, unable to endure the Duke oppression. fled Stuttgart in 1782, Schiller began his literary career. <br> ; 1784, for his outstanding work \"Intrigue and Love\", 1785, his famous poem \"Ode to Joy\" published in 1794, he and Goethe formed a close friendship, and work together to promote the literary movement in Germany and he sponsored by Goethe, it took seven years to complete the masterpiece, \"Wallenstein\" trilogy. later wrote two patriotic scripts the \"Ao Liang girl\" and \"William back Seoul 1805 [lssdjt.cn] Schiller in the poor and sick and had to die. Schiller&#39;s plays <br> \"Wallenstein\" illustrations <br> Schiller, the former residence of <br> < br> stills of Schiller&#39;s part of the works the Chinese translation cover <br> Schiller plays \"Intrigue and Love\", the China Youth Art Theater performances. <br>'
);

?>