<?php

/*
	englist file:1996-12-10
	create time:2013-01-02 02:47:01
*/

return array(
'title'=>'First International Youth Poverty Eradication Award Announced',
'class'=>0,
'cont'=>'October 30 (Rat), December 10, 1996, the first International Youth to eliminate poverty Awards. <br> 1996 12 10, 2009, by the United Nations Development Programme (UNDP) and the China Youth Development Foundation, co-founded the International Youth eliminate poverty Award for the first contest announced in Beijing, Guo seven Paul, Chen Fengxia (female), Li Yong Ren Guoli, Song Fangrong (female, Tujia) 5 honor, the China Youth 18 Youth Award nomination. The five winners <br> parties concerned by the United Nations Development Programme (UNDP) officials and the China Youth Development Foundation, the press and the community composition of the jury after the 23 candidates recommended by the vote in the country. Their deeds are as follows: young farmers, 24-year-old <br> Lishi City, Shanxi Province Guo seven Paul determined to afforestation governance shortage change hometown outlook, four planting pine and cypress 5100 acres, 2100 acres of forest education, reclaiming 450 acres of vegetable fields, so that the former 1.2 mu of barren hills changed its appearance. (Lssdjt.cn) <br> Guangdong Province, South China Normal University, 25-year-old female college student Chen Fengxia, enthusiastic about public welfare, three years ago to give up-off the hometown of life, volunteer to remote mountainous regions of Qingyuan County, Bai Wanzhen when rural teachers, and actively mobilize social forces to care for and help children in poverty-stricken areas, Bai Wanzhen basic education significantly improved. Li Yong, a 17-year-old student <br> Gansu Province, Qingyang Normal School due to family poverty, his mother died young, and his spare time and holidays to work as laborers, and side to side to continue their studies to take care of paralyzed father, has been awarded the & ldquo ; roll student, in 1995 won the first prize in the contest Gansu Division of the National Junior High School Chemistry. Ren Guoli of the Shandong Province Yiyuan <br> a 16-year-old high school students, poor families, and accept the \"Project Hope scholarship funding, hard and self-motivation, strenuously taught and 1996 won the the thirteenth Olympic Physics Competition Shandong Division Principal prize, second prize of National Olympic Physics Competition, now the Department of Physics, Peking University exam-free admission. Wufeng County, Hubei Province, <br> 24-year-old substitute female teacher Song Fangrong devotion to the mountain of education from the age of 15, a person to do a school, both as a teacher in a boarding school and when most of the nurses, wages advanced books for students fees, she taught students pass rate, pass rate, high-resolution, 12 schools in the township for six consecutive years among the top three. <br> judges that the five winners fully embodies the Chinese youth self-improvement, enterprising mental outlook. <br>'
);

?>