<?php

/*
	englist file:1973-7-10
	create time:2013-01-01 23:59:22
*/

return array(
'title'=>'The central task force completion of the Lin Biao and case reports',
'class'=>0,
'cont'=>'July 10, 1973 (on June 11 Guichou), the central task force to complete the Lin Biao and case reports. <br> <br> \"After the events of September\", the central authorities have decided to set up a task force to investigate the Lin Biao counterrevolutionary clique problem. July 10, 1973, the central task force will be \"counter-revolutionary crimes of Lin Piao anti Review Report reported that the CPC Central Committee. [L $ dj¦Ó.c¨­m] <br> \"Report: Lin Biao is a long-hidden in the inner-party bourgeois careerist, conspirator and counterrevolutionary double-dealing, Lin Piao anti rebels a treason counter-revolutionary cabal. &#39;Nine&#39; before and after Lin Biao, Ye Qun, together with his wife, collusion with Chen Boda, Huang Yongsheng, Wu Faxian, Li Zuopeng, Qiu will make and others, formed a bourgeois headquarters of Lin Biao and the chief. In the Plenary Session of the Party&#39;s Ninth II, Lin Piao anti party surprise attack was premeditated. Lin Piao anti-secret preparations to launch a counter-revolutionary coup immediately after the Second Plenary Session of the Party&#39;s Ninth. Report that the emergence of Lin Piao anti fierce class struggle at home and abroad sharp. View to launch a counter-revolutionary coup, Lin Piao anti counterrevolutionary rebels treason offenses, the central panel recommended that the CPC Central Committee: forever expelled bourgeois careerist, conspirator and counterrevolutionary double-dealing, traitor, traitor Lin Piao party; expelled Lin Piao anti-forever The key members of the KMT&#39;s anti-communist, Trotskyist, traitors, spies, revisionist Chen Boda party; permanent exclusion from the main members of the Lin Biao counterrevolutionary clique, entering into the class dissidents within the party, spy, traitor, traitor Ye Qun party; never expelled Lin Biao anti key members of the Party Group Huang Yongsheng, the Wu Faxian, Li Zuopeng Qiu as will Li Xuefeng the party withdraw its inside and outside of all duties; involved in the Lin Biao counterrevolutionary coup other backbone molecules, by the relevant departments responsible for the review, in accordance with the party&#39;s policies, the difference between the situation, put forward matters of opinion, at the Central approval. (Lssdjt.com) August <br> 1973, 20, 2009, the Central Committee approved the report of the task force. April 1, 1982, the CPC Central Committee decision pointed out that the \"report\" Li Xuefeng identified as the main members of the Lin Piao anti does not conform to the facts announced undo this identified, decided to resume his party affiliation. <br> Comments: it was the Ten Marshals, almost done successors Oh <br>'
);

?>