<?php

/*
	englist file:1895-10-10
	create time:2013-01-02 01:51:39
*/

return array(
'title'=>'Lin Yutang&#39;s birthday',
'class'=>4,
'cont'=>'October 10, 1895 (August 22), Yi Wei, Lin Yutang&#39;s birthday. Lin Yutang (third from left) <br>-year-old with parents, brothers and sister. (History today www.lssdjt.com October 10, 2011) <br> 1895, Lin Yutang was born in the Longxi County Sakamoto village. 1901 new primary school in the village of Ming reading. 1905 learning in Xiamen sourcing College. Studying at St. John&#39;s University in Shanghai in 1912. Been learning in the church school, his English is good, thinking deeply influenced by Western culture. After graduating from college in 1916 to teach at Tsinghua University. During this period, studying Chinese classical literature. Went to Harvard University study linguistics in 1919, received a master&#39;s degree; learning and changed to the University of Leipzig, Germany, PhD. 1923 return is Peking University hired to teach English. Published an article in the press in 1924. Professor of English at the university in 1925. Secretary of the Ministry of Foreign Affairs of the KMT government in May 1926, he served as Academia Sinica, English editor. To participate in the China League for Civil Rights in 1931. September 1932, He founded edit \"Analects\", \"Cosmic Wind\" and other publications, essays advocated \"quiet humor\" Lunyu main representatives. Coach to the United States in 1936 and engaged in the writing. To leave the United States in 1938 went to the United Kingdom, Italy, and lived in France. Back in 1943, because he has published some of the outdated, lax people&#39;s speech, opinion formers refutation. In 1947, went to France recommended UNESCO Art and Literature, head to any of the KMT government. 1950, to the United States to continue to engage in writing. Days the wind \"magazine was founded in the United States in 1952. In 1954, he was appointed president of Nanyang University in Singapore. Settled in Taiwan in 1960. 1967, appointed professor by the University of Hong Kong, responsible for the editor of Contemporary Chinese-English dictionary. Died March 16, 1976 in Hong Kong. Is a modern Chinese writer, translator, professor and linguist. There are as many as a dozen or writings. <br> 1919, Lin Yutang and his wife Liu Tsui wind in Boston. Lin Yutang couple <br> daughter. Front row from left: Xiangru Taiyi, so. (Lsjt.net) <br> Tsui Fung and Lu Qin vegetarian couple <br> 1950 in Cannes, France, \"Yang Xin Court <br> 1968 After settle in Taiwan, Lin Yutang in Yangmingshan home piano. The Lin Yutang with Tsui Fung <br> living together for half a century, blazing the joys of trouble, to maintain self-tolerance and mutual love. the Lin Yutang <br> 1969, Tsui Fung (two neutral) married celebration of the 50th anniversary of <br>'
);

?>