<?php

/*
	englist file:1945-5-30
	create time:2013-01-01 20:44:17
*/

return array(
'title'=>'Yan&#39;an premiere opera &quot;White-Haired Girl&quot;',
'class'=>0,
'cont'=>'May 30, 1945 (, Yiyou April 19), Yan&#39;an premiere opera \"White-Haired Girl.\" the <br> ballet \"The White-Haired Girl\" stills <br> 1943 (history com) by Lu Xun Art Institute of collective creation, He Jingzhi, Ding Yi authored writing opera \"White-Haired Girl\" premiered in Yan&#39;an. [Cn, history.] In March, the northwest AFS Jinchaji front of back to Yan&#39;an, brought back a the folklore \"white hair Xiangu\" record this. Described a landlord persecuted peasant girl fled into the mountains alone, insist on living in a cave for years, due to the lack of sun and salt, whole body white hair, because of the theft of the temple for fruit, near the village known as \"white hair Xiangu. \" Later in the rescue of the Eighth Route Army, her liberation. The vivid episode attracted people. Tribute to the forthcoming Seventh Congress of the Party, Lu Yi teachers and students decided to it as a theme, the creation of a new large-scale opera. <br> At first, some people think this is a ghost story, there is no ideological significance; others believe that this subject matter can only be compiled into superstition play. After some discussion, we recognize that the story with a strong legendary contains profound thinking of the old society of people forced into a &#39;ghost&#39; new society &#39;ghost&#39; became a man \". The first game of the show the audience all the representatives of the CPC seven \"Mao Zedong, Zhou Enlai and other Chinese Communist leaders to attend the viewing. Concept, the General Office of the CPC Central Committee to convey Mao Zedong, Zhou Enlai and other Chinese Communist leaders three points: first, the play is very suitable for timely; second, and mom should be shot;, art is successful. Convey to explain these views: the basic problems of the Chinese revolution is the farmers &#39;problems, the so-called farmers&#39; main problem is that farmers against exploitation by the landlord class. After the victory, this class struggle is inevitable sharp reflect this reality, this play will be widely popular. Play in Yan&#39;an more than 30 performances by unprecedented warm welcome, every play to exciting place in the round of applause, prolonged, each to sorrow at the audience is always a cry boos, and some even from the first act to the sixth curtain, tears always is dry, a warrior actually rushed the stage to go kill the drama landlords and mom. People praised on stage emotional blend scenario \"stand up stand up watching play. Some of the village saw the \"White-Haired Girl\" performances, soon mobilize the masses engaged in the struggle against hegemonism and some troops looked after the performance, the soldiers have asked for Yang Bailao, Xi&#39;er revenge, off Kills meritorious boom. (TodayinHistory.cn) <br> opera \"White-Haired Girl\" the stills <br> ballet \"White-Haired Girl\" the stills <br> ballet \"White-Haired Girl Stills <br>'
);

?>