<?php

/*
	englist file:1947-6-30
	create time:2013-01-02 00:18:27
*/

return array(
'title'=>'Liu and Deng advance to the Central Plains',
'class'=>0,
'cont'=>'June 30, 1947 (May 12), Chinese New Year, Liu and Deng advance to the Central Plains. in 1947 6, 30 - July 28 <br> forces night crossed the Yellow River <br>, Liu and Deng field army advancing towards the Central Plains, held in southwest Shandong Battle to uncover strategic offensive prelude. 30 evening, Liu and Deng Field Army main force of 13 million people, in compliance with the instructions of the CPC Central Military Commission, broke through the line of defense of the Yellow River in the KMT army into line operations, and immediately initiated southwestern Shandong Battle. When the Shanxi-Hebei-Shandong-Henan Field Army after the main strong crossed the Yellow River, (L $ dj而.c身m) Chiang Kai-shek hastily summoned, attempt to approach the main Liu and Deng Field Army fighting back water in Yuncheng, Heze, trying to pull out a victory. Our military in number and equipment was not completely crush the enemy key offensive is far worse than the enemy, on the implementation of the strategic shift, which is fully estimated to affect all aspects of war conditions to take bold decisions. Liu Bocheng, [而身d芋y身里h貝 $ 而身ry.c身m] Deng Xiaoping adopted a \"focusing on one point, and suction to aid chew on its side separately operational policy to create a 9 to 15 brigades 4 F KMT army division headquarters half brigades of about 6 million people in the wars, upset the Kuomintang army in the south line of the strategic plan, with the northwest and Shandong Field Army crushed the country party-military key offensive combat. Liu and Deng advance to the Central Plains, opened a prelude to the People&#39;s Liberation strategic offensive, this historic turn of events that shocked the world. U.S. Ambassador John Leighton Stuart exclaimed: China occurred \"Six thirty\" event. American Jack Belden, China Shakes the World, \"a book, an eyewitness wrote:\" I experienced many wars, but never seen this than the Communist Party and later grab crossed the Yellow River more Gaoming outstanding military action. Say that it is clever and well, not quite in this action, although there is no action, all are empty, and the main idea is that the military action - it&#39;s courage, boldness, especially its creative imagination. The leaders of the Communist Party of China in this matter, \"called the Masters: they are good at abandoned unimportant, but stick to the main links. The \"<br> concentrated in the Yellow River bank, Liu, and Deng <br> Liu and Deng the Dabie Mountains Yingshan City entered <br> Liu and Deng army before advancing to the Dabie Mountains (History Today www.lssdjt.com) of Liu Bocheng commander in a general meeting of cadres for mobilization speech <br> Jinjiluyu Field Army to the Dabie Mountains advance <br> Liu, Deng Xiaoping, under the command of'
);

?>