<?php

/*
	englist file:1958-6-30
	create time:2013-01-02 00:20:23
*/

return array(
'title'=>'Completion of the Ming Tombs Reservoir in Beijing',
'class'=>0,
'cont'=>'June 30, 1958 (May 14), the Reform Movement, the Ming Tombs Reservoir in Beijing was completed. <br> Mao Ming Tombs Reservoir&#39;s participation in the labor <br> 1958 June 30, 2009, Beijing Ming Tombs Reservoir project completed. <br> cross locked the Mangshan and Han Bun Lan Hong Dam showing a majestic look. Chairman Mao Ming Tombs Reservoir five words of the title, the masonry are magnified 150 times, the use of white marble inlaid in the dam chest. Crest asphalt road has been opened to traffic. Roadside street lights at night brightly lit. Watson Electric Factory workers who rushed to the generator installed, just wait for the flood storage power generation. The 11.5 km-long lake road is through across the board. (TodayinHistory.cn) the Xiaogushan ready to repair the mid-lake pavilion plus higher future water surface <br> the this to accommodate the more than eighty million cubic meters of water reservoirs is all built with voluntary labor. In the 160 days and nights of January 21 has been started, the 40 million people to the site of labor, more than 8.7 million working days were done. Workers, peasants, PLA officers and soldiers, cadres, teachers and students, business staff, artists, religious believers and residents of the street. They beat the cold of winter, spring sandstorms and summer hot, the whole project is finally completed before the flood season. (TodayinHistory.cn) <br> during the construction of the reservoir, Chairman Mao Zedong and other members of the CPC Central Committee, alternate member of the provinces Municipal and central authority and the person in charge of Beijing, (lssjt.cn) of the Chinese People&#39;s Liberation Army of Marshal and generals, the person in charge of the democratic parties, people&#39;s organizations, the identity of an ordinary laborer to the site to participate in the labor. <br> Ming Tombs Reservoir builders are very grateful to our international friends concerned about the construction of the dam. In more than five months, many countries in our ambassador and embassy staff in Beijing, national experts and foreign guests to visit our country, but also to the site to participate in voluntary labor. Ming Tombs Reservoir, inaugurated on July 1. Reservoir builders and farmers near the site for a total of fifteen people held a grand celebration to mark the completion of the reservoir of all engineering victory. <br>'
);

?>