<?php

/*
	englist file:1979-11-14
	create time:2013-01-02 01:34:46
*/

return array(
'title'=>'The U.S. froze Iranian government assets in the United States',
'class'=>0,
'cont'=>'November 14th, 1979 (, Kang Xi September 25), the U.S. froze Iranian government assets in the United States. <br> 1979 11 14, Iran announced that it will be taken out from the Bank of America $ 12 billion of its deposits, and these deposits deposited no with the U.S. boycott of the banks of European countries to buy Iranian oil. <br> this decision Banisadr, Iran&#39;s acting Foreign Minister, announced in a press conference held by Tehran. The (history TodayOnHistory.com) <br> he said, the transfer of these funds, the requirements put forward by the Central Bank of Iran \"brothers and sisters\", and has been approved by the Iranian Revolutionary Committee. <br> He also said that Iran&#39;s interests in the United States is worth about $ 50 billion. <br> Iranian government intends to extract $ 12 billion from the United States deposits news, financial markets in Western Europe on the 14th cause fluctuations: gold prices, the U.S. dollar plunged. (L $ dj而.身r阱) <br> important financial market in Western Europe such as London, Frankfurt, Zurich and Paris, the exchange rate of the U.S. dollar against the major currencies of Western Europe fell. In the London market, the number of each dollar deutsche mark reduced by almost two Finney (the one mark equal to one hundred Finney), the number of exchange of CHF reduced two centimes (one franc equal to one hundred centimes ). Market brokers, holders of dollars in selling dollars. <br> original has been reduced to $ 384.5 per ounce of gold prices in London and Zurich on the market in the morning of the 14th, but rose to 391.25 and $ 389, respectively. <br> London market broker, said: \"The news from Iran caused a storm in the market. \"Some of the brokers on the financial markets later in the day when the price changes more relaxed. <br> U.S. President Jimmy Carter issued an order to freeze all the property of the Crown of Iran in the United States, including bank deposits. (有身d芋y身里h貝 $ 而身ry.c身m) <br> White House Press Secretary Powell said in a statement, \"the news that the Iranian government is prepared to withdraw its funds, this command is the answer to this message. \"<br> Said in a statement,\" This command does not involve personal payments, involves only the deposits of the Iranian government, the Central Bank of Iran and other entities controlled by the Bank and its overseas branches in the United States. \"<br> About the number of deposits in Iran, the White House statement said:\" The exact amount involved could not be verified. \"<br>'
);

?>