<?php

/*
	englist file:1949-1-14
	create time:2013-01-01 21:48:48
*/

return array(
'title'=>'Mao Zedong published the current situation Statement',
'class'=>0,
'cont'=>'(Lunar twelfth lunar month XVI), January 14, 1949, Mao issued the current situation declarations. and other central leaders <br> Mao Zedong photo with the participants <br> the main Kuomintang troops in only two-and-a-half years, from July 1946 to January 1949, Chiang Kai-shek to launch a full-scale civil war has basically been wiped out, Chiang Kai-shek has been driven into an impasse. People&#39;s Liberation War victory rapid development of the situation in the New Year&#39;s Day of 1949, Chiang Kai-shek had to pretend to summation, issued a statement to the summation of the Communist Party of China. <br> false peace offensive against Chiang Kai-shek, Chairman Mao Zedong on behalf of the Chinese Communist Party issued a famous statement of the current situation on January 14, 1949, statement eight conditions to achieve real peace. (TodayinHistory.cn) <br> statement of the Communist Party of China: Although the Chinese People&#39;s Liberation Army has sufficient strength and sufficient reason, sure, not be long before the time of all to eliminate residual military forces of the Kuomintang government; In order to end the war quickly, to achieve true peace, and to reduce the suffering of the people, the Communist Party of China is willing and Nanjing Kuomintang government of Chiang Kai-shek and other Kuomintang local government and military blocs, the peace negotiations on the basis of the following conditions. These conditions are: <br> (a) the punishment of war criminals; (b) by repealing the bogus constitution; (c) by repealing the pseudo law system; (d) In accordance with the principles of democracy adaptation of all reactionary army; (e) confiscation of bureaucratic capital; (f) reforming the land system; (g) the abolition of the traitorous treaties; (VIII) to convene no reactionaries participate Political Consultative Conference, the establishment of a democratic coalition government, to receive all the powers of the Nanjing Kuomintang government and belongs to all levels of government. <br> that the Communist Party of China, the eight conditions reflect the general will of the entire Chinese people, just under eight conditions created by the peace, truly democratic peace. on behalf of the Communist Party of China&#39;s current situation statement <br> Chairman Mao Zedong, won the unanimous endorsement and support of the people of the whole country and the democratic parties. Already reach the liberated areas of various democratic parties, each of the people groups on behalf of figures and other democrats Li Jishen, Shen Junru Ma Xulun, Guo and other 55 people on January 22 jointly issued statement resolutely uphold Chairman Mao Zedong eight peaceful conditions, against the Kuomintang Chiang Kai-shek false peace conspiracy. (L $ j¦Ó.c¨½) <br>'
);

?>