<?php

/*
	englist file:2001-8-14
	create time:2013-01-02 00:42:35
*/

return array(
'title'=>'A domestic Maglev passenger Changchun Car Company completed offline',
'class'=>0,
'cont'=>'August 14, 2001, June 25 (Government House), a domestic Chinese maglev passenger in Changchun Car Company completed offline. In In 2001, August 14, 2010, a domestic Chinese maglev passenger in Changchun Car Company completed offline. <br> by Southwest Jiaotong University, Changchun Car Company and Zhuzhou Electric Locomotive Research Institute jointly developed a domestic maglev passenger passenger car plant in Changchun completed offline. <br> According to the person in charge of this research project, the Institute of Southwest Jiaotong University Maglev Train Maglev technology company level III Professor, car maglev passenger special vehicle production for the the \"the Qingcheng Mountain maglev train engineering model line is often guide suck Floating magnetic levitation vehicle, the electromagnetic suction vehicles float, always keep track pitch between 8-10 mm, linear motor drive operating speed of 60 kilometers per hour, the highest test up to 100 kilometers per hour. This maglev passenger cars off the assembly line yesterday body length of 11.2 meters, 2.6 meters wide, equipped with 28 seats, two tons of load. The bodywork beam welding of aluminum alloy plate body, light weight, and weight of only 16 tons, has a smooth and comfortable ride, low noise, pollution, etc. Since there is no mechanical friction between the wheel and rail vehicles, vehicle operation. the <br> 1998 in December, Changchun Car Company, Southwest Jiaotong University, Zhuzhou Electric Locomotive Research Institute and Qingcheng Mountain maglev train Engineering Co., Ltd. signed a technical cooperation agreement to jointly develop China&#39;s first maglev train project demonstration line and December 30, 1999 to complete the design task. <br> It is reported that this maglev passenger cars will be the end of this month arrived in Chengdu, and the performance test is completed first steel test line in 43 meters of Southwest Jiaotong University campus, and then shipped to Qingcheng Mountain to do tourism business operations and practical experiments. For this horse, \"horse\" maglev train project Qingchengshan Benz model line are speeding up the construction of the project line is more than 400 meters in length, will soon be completed and put into use. <br> Review: This marks after Germany and Japan, China has become the third country to master maglev Bus Technology. <br>'
);

?>