<?php

/*
	englist file:1994-10-14
	create time:2013-01-02 01:05:21
*/

return array(
'title'=>'Israeli rescue the hostages failed',
'class'=>0,
'cont'=>'(Awake, September tenth day), October 14, 1994, Israeli rescue the hostages failed. <br> 1994 10 14 evening, in the Occupied Palestinian the soil wax Mara Bill - Na Bala village. The days just dusk, most of the villagers reunion dinner at home, quiet little village extraordinarily quiet. (History cn) <br> about this time, an Israeli commando suddenly sneaked into the village, to the 9th kidnapped Israeli soldiers Walker Klinsmann \"Hamas&#39; armed in the village 9 sub The dens launched lightning attacks, to rescue Walker Klinsmann detained there. However, the unexpected, \"Hamas\" rented the doors and windows of the house for the detention of the hostages have already been firmly blocked. Israeli commandos break the first door, found inside a wall, continue to attack, was the stubborn resistance of the Hamas militants, Israeli commandos less than Jiugong last shall No explosives blasted the door. <br> up to 40 minutes of fierce fighting, Walker Klinsmann, three Hamas militants were killed and one captured. Israeli side, a commando officers were killed and another 12 injured commandos. (History com) 3 days shocked the Israeli National and impact to the end of this hostage crisis of the Palestinian-Israeli peace talks, but paid a high price. <br> 11, the Organization of the Islamic Resistance Movement \"Hamas\" armed \"Azeddine - Qassam\" Detachment statement, announced that the missing Israeli soldiers Walker Klinsmann has been kidnapped by the organization and fertile ID card, guns, and his image display box on the tape, the deadline for the Israeli authorities to release 200 Hamas detainees at 21 o&#39;clock on the 14th, or they will kill Walker Klinsmann. <br> After the incident, Israeli Prime Minister Yitzhak Rabin and Palestinian leader Yasser Arafat for urgent consultations and frequent contact. Israeli troops in Gaza closed, carried out a large-scale search in the occupied territories. Gaza autonomous Palestinian police also launched a large-scale \"mop-up\", and also arrested 200 Hamas members, to find Walker Klinsmann&#39;s whereabouts. <br> International Red Cross also made contacts with \"Hamas\" and reached the agreement will kill hostage deadline postponed 24 hours. Concerned will continue to be busy for a political solution to the crisis, the Israeli military has taken the above attacks. <br> Israeli Prime Minister and Defense Minister Yitzhak Rabin after the attacks immediately held a press conference, announced that the kidnapped to soldiers Walker Klinsmann has been killed by \"Hamas\" molecules. He said, he decided to take the attacks to assume full responsibility. Rabin said that the reason he made the decision because \"Hamas\" in an attempt to kill more Israelis and strangle Middle East peace in exchange for the release of terrorists by kidnapping Walker Klinsmann. Thus, his decision is consistent with the policies of Israel does not compromise to terrorists. <br>'
);

?>