<?php

/*
	englist file:2002-10-18
	create time:2013-01-02 01:24:59
*/

return array(
'title'=>'China&#39;s first national plan introduced',
'class'=>0,
'cont'=>'September 13th (Horse), October 18, 2002, China&#39;s first national plan introduced. <br> 2002 10 18, the National Informatization Leading Group approved and promulgated the \"Tenth Five Year Plan for National Economic and Social Development of information technology major special planning\", which is the \"10th Five-Year Plan\" period of China&#39;s national economy and special plans for one of the ten key social development of the preparation of the first national planning. <br> \"special plan\" is defined in the connotation of information, pointed out that \"information technology is information technology is widely used as the leading information resource for the core-based information network, the information industry as the support, information rely on talent and regulations policy, an integrated system of standards for the protection of \"security, clear the\" 10th Five-Year Plan \"period of advancing the national economy and social development policy, namely the\" overall planning, resource sharing, application-driven, market-oriented, reliable, seek practical results. \" <br> \"special plan\" pointed out, \"15\", the national economy and social informatization level to a new level, the telecom operation and electronic information product manufacturing industries accounted for 7% of the gross domestic product (GDP) ; create favorable conditions for network size, capacity ranks first in the world to meet the basic needs of the information technology development, universal service capabilities continue to improve, participate in the development of information technology for the central and western regions of the network infrastructure is weak, the majority of the rural areas and in low-income ; information services industry will continue to maintain a rapid growth momentum; further improve the level and scale of the electronic information product manufacturing, electronic information product manufacturing industries accounted for 3.3% of the gross domestic product (GDP); Information has become an important means to improve the quality of citizens; informatization talent The team has grown. <br> \"special plan\" proposed, \"15\", the three major tasks of China&#39;s information technology efforts to complete the promotion and application of information technology and modern information infrastructure and accelerate the development of electronic information industry. <br>'
);

?>