<?php

/*
	englist file:1530-2-18
	create time:2013-01-02 08:43:04
*/

return array(
'title'=>'Japan&#39;s Warring States Army of God, Echigo daimyo Uesugi Kenshin was born',
'class'=>4,
'cont'=>'February 18, 1530, the first month twenty (GY), born in Japan&#39;s Warring States Army of God, Echigo daimyo Uesugi Kenshin. Warring States military god, <br> - Uesugi Kenshin <br> (also known as the long tail Kagetora 丹 尹 su gi 仃 氏 仄 氏 (L $ dj而.c身m) Uesugi Kenshin) <br> (February 18, 1530 April 19 Day -1578) <br> an active in Japan&#39;s Warring States Period daimyo, the Echigo State guardian on behalf of the long tail is King youngest son, the immature name \"Tiger Chiyoda\". Called long tail Kagetora adult. Have three adopted son, whose name attractions, Kagetora and political prosperity. In the inherited Kanto tube collar Uesugi surname, (l $ dj而.身r阱) and has any Kanto tube collar the Uesugi constitutional Muromachi shogun Ashikaga Yoshiteru Ciming, it is also known as the Uesugi political tiger, the Uesugi Hui tiger. The monk Fahao Kenshin. Because of his high command of the military capabilities, so in the Hereafter known as the Dragon of Echigo, generally known as the Army of God. The official position from four shells are less Bute and four under Guards Major General, after the death of gifts back are two. In 1548, Kenshin became Governor of the long tail and everyone, and its outstanding ability to unify Echigo. Since efforts to restore the the Muromachi shogunate old order, Takeda Shingen and the south, southeast Hojo Kang multiple combat, (L $ dj而.妨壯T) the Takeda Shingen five Kawanakajima Gassen, (on www.TodayOnHistory com) and Hojo&#39;s health Kanto troupe - the famous Odawara battle are the Japanese military in the history of wars. Oda Nobunaga elimination of the Muromachi shogunate move <br> 1577, Kenshin began Oda Nobunaga expedition the Natori River (known as hand Natori River Battle) defeated Oda Army in the hand. But the following year in spring mountain and died due to cerebral hemorrhage. (Lssdjt.com) <br> Kenshin Although invincible, known as the \"Dragon of Echigo\" Warring States the strongest, \"the generals, but Buddhist once very contradictory. In particular, the Buddhist God of War:? Into to take advantage of the plate tonight? Kerry? Into taking advantage of the disc variegate screen? Rage? Tie? Ldquo;?? Rdquo; senki for jihad. Advocating \"justice\", and its behavior in the troubled times of the Warring States Period, is very special. the authoritative <br> Japanese history scholars Sakamoto Taro evaluation Kenshin said in his book \"History of Japan Summary:\" rage to impermanence, mad contention scuffle whom the generals middle, Uesugi Kenshin to revere Buddha Shigehito Lun, yet integrity, good knowledge of high section of people in known, it was worthy of chaos breath of fresh breath. \"Can be described as a very insightful summary. the Uesugi Kenshin <br> which <br> Samurai Warriors'
);

?>