<?php

/*
	englist file:1997-3-18
	create time:2013-01-01 22:43:36
*/

return array(
'title'=>'Nanning-Kunming Railway opened to traffic',
'class'=>0,
'cont'=>'March 18, 1997, the 10th day (Landmarks), the Nanning-Kunming Railway opened to traffic. The Nankun railway <br> diagram <br> March 1997, the Nanning-Kunming railway line celebration rally in Guangxi Baise held. <br> Nanning-Kunming railway east from Nanning, west of Kunming, the north red berries, and a total length of 898.7 km, a national trunk electrified railway, the annual transportation capacity of the recent 10 million tons, forward 2000-30000000 t. <br> Nanning-Kunming railway projects include: construction length of 863.04 kilometers of the positive line engineering; introduction of Nanning, Kunming hub renovation and expansion project and the main line electrification project. <br> Nanning-Kunming railway is China Following the Chengdu-Kunming Railway, built in the dangerous mountain and a grown up Link, after the completion of the railway, the east railway connecting Hunan, Guangxi, Li Zhan, Southern anti-West and the Chengdu-Kunming, Guizhou Kunming Railway even communicate in southwest China and the southeast coast of the most convenient channel Guangxi Fangcheng, Qinzhou, Beihai Port, together, constitute the sea southwest of the channel to accelerate the region&#39;s economic development is of great significance. <br> Nanning-Kunming railway in the construction of the most complex geological conditions mountain railway lines, high gas seam, high stress, Sage gushing, large landslide, cave, rock, soft soil, earthquake fault zones serious geological disease clouds the trunk through the more than 90% of the area known as the the geological \"maze\", here is the most dangerous construction environment, to overcome all kinds of geological disease, the most intensive high-tech applications. <br> Nanning-Kunming railway, our cost of the most highest railway, the railway crossing has quality phosphate rock Kunyang Phosphate Nanning-Kunming railway 9392 meters long rice flower tunnel is the longest single-track railway tunnel. Known as \"the first insurance hole\" near Guizhou Province hongguo town home JIAZHUQING tunnel, this tunnel is China&#39;s first direct tunnel through the high gas seam, its day gushing over 80,000 m3, the country&#39;s largest tunnel water inflow, and the emergence of China&#39;s first third case in the world of highland stress phenomenon. Nanning-Kunming railway, <br> home JIAZHUQING Tunnel <br> by the Shimizu River Bridge is one of the world&#39;s highest railway bridge piers is the first one hundred meters high pier, the main span of 128 meters in the national trunk Railway maximum span. Bridge the Qian column at the junction of Badu Nanpanjiang known as the \"Divine Bridge\", which in domestic railway bridge first used the new technology of the V-shaped support. the Nanpan River Bridge <br> of the Qingshuihe Bridge <br> <br> Badu'
);

?>