<?php

/*
	englist file:1999-4-18
	create time:2013-01-01 22:04:52
*/

return array(
'title'=>'Ye Fei&#39;s death, the famous high-ranking officers of the People&#39;s Liberation Army, the anti-Japanese hero',
'class'=>3,
'cont'=>'April 18, 1999 (March 3rd) JiMao, Ye Fei, the famous high-ranking officers of the People&#39;s Liberation Army, Japanese hero&#39;s death. <br> Ye Fei (1914-1999), formerly known as Ye Qiheng. Ye Fei is a well-known senior generals in the People&#39;s Liberation Army. Origin Fujian Nanan. Born in 1914 in the Philippines, Quezon Province, a Chinese family. 1918 returnees. 1928 joined the Chinese Communist Youth League. Transferred to the Communist Party of China in March 1932. The same year to Mindong involved in the creation of Mindong Soviet Area and the guerrilla. Former Communist China the Mindong recordership secretary, (Lssdjt.com) Mindong Military and Political Committee Chairman, political commissar of the Red Army the Mindong independent division, leading military and civilian adhere extremely difficult three-year guerrilla war. <br> Sino-Japanese War After the outbreak of any of the New Fourth Army 3rd Detachment 6 regiment. In late July 1939, the headquarters team broke into the Shanghai Hongqiao International Airport, destroying enemy planes 4, shocking the Japanese puppet expanded my party and the political influence of the New Fourth Army. South Anhui Incident in 1941, he served as the New Fourth Army Division 1 Travel Tours president and political commissar, deputy division commander. March 1944, directing the famous Battle of the axle, sweep puppet stronghold in one fell swoop, wiped out the Japanese more than 500 people by the superiors commended. In 1945, he was appointed commander of the New Fourth Army Division Division President Su Zhongjun and the Chinese Communist Party of the Soviet Union in the District Committee secretary, Jiangsu, Zhejiang Military Region deputy commander, helped to lead to the establishment of Jiangsu, Zhejiang and Anhui behind enemy lines New Area, participate in command Tianmushan Battle. Distinguished itself in the War of Resistance Against Japan, Ye Fei highlighted the danger, made a significant contribution to the nation&#39;s independence and liberation. <br> Liberation War, served as the commander of the first column of Shandong Field Army, the commander of the first column of the East China Field Army commander and political commissar, the l-Corps deputy commander of the 1st Column, Third Army Corps commander, Fujian Military District Commander. After the founding of the People&#39;s Republic of China, the former first secretary of the CPC Fujian Provincial Committee and governor of Fujian Province, the deputy commander of the Nanjing Military Region, Fuzhou Military Region commander and political commissar, Minister of Communications, (lssjt.cn) People&#39;s Liberation Army Navy first political members, Commander, Sixth, Seventh NPC Standing Committee vice chairman and other staff. In 1955, he was awarded the rank of general. April 18, 1999, died in Beijing. <br>'
);

?>